import type { Metadata } from "next";
import { Chapter, Objetivos, Idea, Cuidado, Comprueba, Guardar, ChapterNav } from "@/components/Book";

export const metadata: Metadata = { title: "Transparencia del AI Act: audita chatbots y contenido sintético | Aulafy", description: "Audita cómo una pyme informa sobre chatbots, deepfakes y contenido generado o manipulado con IA según el artículo 50 del AI Act.", keywords: ["AI Act artículo 50", "transparencia chatbots", "contenido generado IA", "etiquetar deepfake"], alternates: { canonical: "/cursos/ia-pymes/transparencia-ai-act-articulo-50" } };

export default function Page() { return <Chapter crumb="IA para pymes y autónomos" title="Transparencia del AI Act: audita chatbots y contenido sintético" icon="legal" lead={<>La transparencia no consiste en añadir una etiqueta genérica a todo: primero identifica si tu empresa es proveedor o deployer y qué obligación concreta se activa.</>} courseHref="/cursos/ia-pymes" courseLabel="IA para pymes y autónomos">
  <Objetivos><ul><li>Localizar chatbots y contenidos generados o manipulados con IA.</li><li>Distinguir información al interactuar con una IA, marcado machine-readable y aviso a personas expuestas.</li><li>Guardar una auditoría fechada sin presentar el ejercicio como asesoramiento jurídico.</li></ul></Objetivos>
  <div className="prose"><h2>Qué dice la guía oficial</h2><p>Las directrices de la Comisión Europea sobre el artículo 50 explican obligaciones de transparencia para ciertos sistemas. Se aplican desde el 2 de agosto de 2026. Entre los casos descritos están informar a quien interactúa directamente con una IA, marcar de forma detectable el contenido generado o manipulado y avisar a las personas expuestas a deepfakes, sistemas de reconocimiento emocional o textos sobre asuntos de interés público sin revisión o control editorial humano.</p><p>Existe un matiz importante: la Comisión también describe un periodo transitorio para determinados sistemas generativos comercializados antes del 2 de agosto de 2026, hasta el 2 de diciembre de 2026. No conviertas una fecha de inicio en una respuesta universal: comprueba el sistema, el rol de tu empresa y la guía vigente.</p><h2>Auditoría en cinco pasos</h2><ol><li>Lista cada chatbot, asistente y canal público.</li><li>Indica si tu empresa lo provee, lo despliega o solo lo usa internamente.</li><li>Revisa qué contenido se genera o modifica y si hay revisión editorial.</li><li>Comprueba el aviso visible y el marcado técnico cuando corresponda.</li><li>Guarda captura, URL, responsable, fecha y acción correctora.</li></ol><h2>Fuentes primarias</h2><ul><li><a href="https://digital-strategy.ec.europa.eu/es/library/guidelines-transparency-obligations-providers-and-deployers-ai-systems" rel="noreferrer">Directrices de la Comisión sobre obligaciones de transparencia</a>.</li><li><a href="https://digital-strategy.ec.europa.eu/es/policies/guidelines-transparency-ai-generated-content" rel="noreferrer">Guía de transparencia del contenido generado por IA</a>.</li><li><a href="https://digital-strategy.ec.europa.eu/es/factpages/quick-facts-transparency-rules-ai-systems" rel="noreferrer">Resumen oficial de reglas de transparencia</a>.</li></ul></div>
  <Idea><strong>Acción de la misión:</strong> audita un chatbot y tres piezas de contenido sintético de tu organización; registra si requieren aviso, marcado detectable, revisión humana o ninguna acción justificada.</Idea>
  <Cuidado>Esta misión no determina por sí sola el cumplimiento legal. Las obligaciones dependen del sistema, el rol, el sector y la jurisdicción; consulta a la persona responsable de cumplimiento o protección de datos.</Cuidado>
  <Comprueba>Guarda una tabla antes/después con URL o archivo, tipo de sistema, aviso aplicado, evidencia y fecha de próxima revisión.</Comprueba>
  <Guardar>Entrega `auditoria-transparencia-ai-act.csv` y una captura de cada aviso publicado. No guardes datos personales innecesarios en la evidencia.</Guardar>
  <ChapterNav next={{ href: "/cursos/ia-pymes/diagnostico-piloto", label: "Diagnóstico y primer piloto de IA para una pyme" }} />
 </Chapter>; }
