import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Chapter, Objetivos, Idea, Cuidado, Comprueba, Guardar, ChapterNav, Terminal } from "@/components/Book";

type Lesson = { title: string; lead: string; objectives: string[]; body: string; action: string; caution: string; next?: string };

const lessons: Record<string, Lesson> = {
  "que-puede-hacer-llm-datos": { title: "Qué puede y qué no puede hacer un LLM con datos tabulares", lead: "Un modelo puede proponer una consulta, pero los datos y el motor deben decidir el resultado.", objectives: ["Separar lenguaje natural, consulta y resultado.", "Identificar cuándo una respuesta necesita evidencia.", "Escribir el primer contrato del asistente."], body: "La primera regla del curso es no pedirle al modelo que calcule de memoria. El flujo seguro es: pregunta → consulta reproducible → ejecución en DuckDB/SQLite → resultado → explicación con referencia a columnas y filas. El LLM ayuda a traducir y explicar; el motor de datos sigue siendo la fuente de verdad.", action: "Escribe tres preguntas sobre un CSV ficticio y, para cada una, anota qué consulta y qué evidencia exigirías.", caution: "No subas datos de clientes a un servicio externo para probar una idea. Empieza con datos sintéticos o anonimizados.", next: "entorno-reproducible" },
  "entorno-reproducible": { title: "Crea un entorno reproducible con Python y uv", lead: "Una analítica fiable empieza con un proyecto que otra persona pueda instalar y ejecutar.", objectives: ["Crear un proyecto aislado.", "Fijar dependencias y versión de Python.", "Separar código, datos y resultados."], body: "Usa `uv init` para crear el proyecto y añade pandas, polars, duckdb y pyarrow solo cuando los necesites. Guarda la configuración en `pyproject.toml`, excluye datos privados con `.gitignore` y crea carpetas `data/`, `src/`, `reports/` y `tests/`.", action: "Crea la estructura, ejecuta un script que imprima la versión de Python y guarda el resultado en `reports/entorno.txt`.", caution: "No dependas de paquetes instalados globalmente ni incluyas `.env` en Git.", next: "cargar-datos-seguro" },
  "cargar-datos-seguro": { title: "Carga CSV y Excel sin perder tipos ni privacidad", lead: "Leer un archivo no es solo llamar a una función: hay que comprobar codificación, columnas y límites.", objectives: ["Detectar encoding y separadores.", "Revisar tipos de fechas, importes y textos.", "Limitar tamaño y ubicación de entrada."], body: "Carga primero una muestra y registra nombre, tamaño, columnas y tipos. Rechaza rutas fuera de la carpeta permitida. Para Excel, conserva la hoja elegida y documenta si las fórmulas se leen como valores. Un archivo mal formado debe producir un error explicable, no una tabla silenciosamente vacía.", action: "Implementa una función `load_table(path)` que acepte solo `data/incoming/`, limite el tamaño y devuelva un resumen de columnas.", caution: "CSV y hojas pueden contener fórmulas o instrucciones maliciosas. Trátalos como datos, nunca como órdenes.", next: "perfilado-datos" },
  "perfilado-datos": { title: "Perfila un dataset antes de pedirle nada a la IA", lead: "El perfilado revela qué preguntas son posibles y qué errores arruinarían una respuesta.", objectives: ["Medir nulos, duplicados y cardinalidad.", "Detectar fechas e importes sospechosos.", "Guardar un perfil legible."], body: "Calcula filas, columnas, nulos, valores únicos, rangos y duplicados. Para cada campo define una expectativa: importe no negativo, fecha válida, identificador no vacío. El perfil es una evidencia de entrada que podrás comparar tras una limpieza.", action: "Genera `reports/profile.json` y un resumen Markdown con tres anomalías y cómo las revisarías.", caution: "No borres anomalías automáticamente: una devolución o un importe negativo puede ser un hecho real.", next: "limpieza-verificada" },
  "limpieza-verificada": { title: "Limpieza asistida por IA con verificación humana", lead: "La IA puede sugerir transformaciones; una persona debe aprobar las reglas que cambian datos.", objectives: ["Separar propuesta y aplicación.", "Conservar valores originales.", "Probar reglas con ejemplos."], body: "Pide al modelo que proponga reglas en JSON: columna, condición, transformación y justificación. Ejecuta solo reglas permitidas y escribe un registro de cambios. Conserva el original y compara antes/después.", action: "Haz que el modelo proponga cómo normalizar fechas y espacios; aprueba manualmente una regla y escribe un test para ella.", caution: "Nunca uses una salida de texto libre como código ejecutable ni sobrescribas el dataset original.", next: "lenguaje-natural-sql" },
  "lenguaje-natural-sql": { title: "De lenguaje natural a SQL visible y verificable", lead: "La consulta generada debe verse, validarse y ejecutarse en un motor limitado.", objectives: ["Construir un esquema para el modelo.", "Bloquear operaciones peligrosas.", "Mostrar SQL y resultado."], body: "Entrega al modelo nombres de tablas, columnas y tipos, no filas privadas innecesarias. Permite inicialmente solo `SELECT`, añade un límite de filas y valida tablas/columnas contra el esquema. La interfaz debe mostrar la consulta antes o junto al resultado.", action: "Convierte una pregunta de ventas en SQL DuckDB, ejecútalo con un límite y guarda pregunta, SQL y resultado.", caution: "No permitas `DROP`, `DELETE`, `UPDATE`, extensiones ni acceso a rutas arbitrarias.", next: "pandas-polars-duckdb" },
  "pandas-polars-duckdb": { title: "Elige entre pandas, Polars y DuckDB", lead: "La herramienta correcta depende del tamaño, la operación y la claridad que necesita el equipo.", objectives: ["Comparar tres enfoques.", "Elegir por evidencia, no por moda.", "Medir tiempo y memoria."], body: "Pandas es didáctico y flexible; Polars ayuda con transformaciones eficientes; DuckDB permite SQL sobre CSV y Parquet sin montar un servidor. Puedes combinarlos: DuckDB para consulta, Polars para pipelines y pandas para exploración pequeña.", action: "Ejecuta la misma agregación con dos herramientas y registra tiempo, memoria y legibilidad.", caution: "No optimices antes de tener una medición y una consulta correcta.", next: "rag-tablas-local" },
  "rag-tablas-local": { title: "RAG sobre tablas y bases de datos locales", lead: "Recuperar metadatos y resultados es más seguro que pedir al modelo que recuerde todo el dataset.", objectives: ["Distinguir esquema, filas y documentos.", "Añadir metadatos de origen.", "Devolver citas verificables."], body: "Para tablas, empieza recuperando esquema, descripciones y resultados agregados; no conviertas cada celda en un vector sin una razón. Cada fragmento debe conservar archivo, hoja, tabla, consulta y fecha. Si no hay evidencia, el asistente debe decirlo.", action: "Diseña un objeto de contexto con `source`, `query`, `columns` y `rows`, y úsalo en una respuesta con citas.", caution: "RAG reduce búsquedas ciegas, pero no elimina alucinaciones ni errores de permisos.", next: "informes-con-evidencia" },
  "informes-con-evidencia": { title: "Genera informes con citas y evidencia", lead: "Un informe útil deja claro qué se calculó, con qué datos y qué queda por revisar.", objectives: ["Separar hechos, interpretación y recomendación.", "Citar consultas y periodos.", "Marcar incertidumbre."], body: "Usa una plantilla con resumen, método, resultados, limitaciones y fuentes. Las cifras deben enlazar a una consulta o archivo. Las recomendaciones se etiquetan como interpretación, no como dato observado.", action: "Genera un informe Markdown de una página con dos cifras, sus consultas y una limitación explícita.", caution: "No presentes una explicación fluida como prueba de que el cálculo es correcto.", next: "dashboard-streamlit" },
  "dashboard-streamlit": { title: "Publica un dashboard local con Streamlit", lead: "La interfaz debe enseñar la pregunta, la fuente y el resultado, no esconder la consulta.", objectives: ["Crear filtros reproducibles.", "Mostrar fecha y fuente.", "Degradar con un mensaje claro si falla el modelo."], body: "Construye una pantalla con carga controlada, filtros, tabla de resultados y un panel de evidencia. Mantén las consultas en funciones testeables; la UI solo orquesta. Añade un modo demo con datos ficticios para no bloquear el aprendizaje.", action: "Crea una vista que filtre ventas por periodo y muestre la consulta y el archivo de origen.", caution: "No expongas Streamlit a Internet sin autenticación, límites y una revisión de datos.", next: "evaluar-respuestas" },
  "evaluar-respuestas": { title: "Evalúa exactitud, consulta y evidencia", lead: "Una demo que funciona una vez no es un sistema fiable.", objectives: ["Crear un conjunto pequeño de casos.", "Medir respuesta, consulta y evidencia.", "Registrar regresiones."], body: "Prepara preguntas con respuesta conocida, casos ambiguos y preguntas fuera de alcance. Puntúa por separado si la consulta es correcta, si el resultado coincide, si la cita permite reproducirlo y si la respuesta se abstiene cuando falta información.", action: "Escribe diez casos y una tabla de evaluación; ejecuta dos versiones del prompt y compara.", caution: "No uses solo una valoración subjetiva del texto final.", next: "privacidad-costes-modelos" },
  "privacidad-costes-modelos": { title: "Privacidad, costes y límites de modelos locales", lead: "Local no significa automáticamente seguro, gratis ni exacto.", objectives: ["Dibujar el flujo de datos.", "Estimar coste y recursos.", "Elegir local, API o híbrido."], body: "Ollama puede mantener la inferencia en tu equipo, pero logs, conectores y copias pueden sacar datos. Documenta hardware, modelo, tamaño de contexto, latencia y consumo. Si usas API, calcula tokens y define presupuesto por tarea.", action: "Completa una ficha de decisión para tu dataset: dónde viajan los datos, qué modelo usarías y qué coste máximo aceptarías.", caution: "No prometas privacidad absoluta ni equivalencia entre modelos locales y servicios cloud.", next: "reportes-programados" },
  "reportes-programados": { title: "Automatiza un informe periódico con revisión", lead: "La automatización debe producir un borrador y una evidencia antes de enviar nada.", objectives: ["Separar extracción, análisis y publicación.", "Añadir logs y reintentos limitados.", "Introducir aprobación humana."], body: "Programa un script o workflow que lea una entrada conocida, ejecute consultas, genere un informe y lo deje en una carpeta de borradores. Registra inicio, fin, versión, filas procesadas y errores. El envío se mantiene manual hasta superar la evaluación.", action: "Ejecuta el pipeline dos veces con el mismo dataset y verifica que produce el mismo resultado y un log legible.", caution: "No programes envíos ni modificaciones de sistemas reales durante el primer piloto.", next: "entrega-auditoria" },
  "entrega-auditoria": { title: "Entrega el asistente con checklist y modo degradado", lead: "El proyecto termina cuando otra persona puede entenderlo, probarlo y detenerlo.", objectives: ["Documentar instalación y fuentes.", "Definir modo degradado.", "Preparar un checklist de auditoría."], body: "Entrega repositorio, dataset ficticio, instrucciones, tests, ejemplos de preguntas, consultas visibles, informe y dashboard. El modo degradado debe seguir permitiendo explorar datos sin modelo: consultas predefinidas, mensajes de error y exportación. Incluye responsable, backup, fecha de revisión y límites.", action: "Pide a otra persona que clone el proyecto y complete el flujo sin tu ayuda; registra cada bloqueo y corrígelo.", caution: "Un asistente no está listo para datos reales hasta revisar permisos, retención, backups y resultados incorrectos.", next: undefined },
};

export function generateStaticParams() { return Object.keys(lessons).map((lesson) => ({ lesson })); }

export async function generateMetadata({ params }: { params: Promise<{ lesson: string }> }): Promise<Metadata> {
  const { lesson } = await params;
  const item = lessons[lesson];
  return item ? { title: `${item.title} | Aulafy`, description: item.lead, alternates: { canonical: `/cursos/ia-datos-analitica/${lesson}` } } : {};
}

export default async function Page({ params }: { params: Promise<{ lesson: string }> }) {
  const { lesson } = await params;
  const item = lessons[lesson];
  if (!item) notFound();
  const next = item.next ? lessons[item.next] : undefined;
  return <Chapter crumb="Asistentes analíticos locales" title={item.title} icon="spreadsheet" lead={item.lead} courseHref="/cursos/ia-datos-analitica" courseLabel="Asistentes analíticos locales">
    <Objetivos><ul>{item.objectives.map((objective) => <li key={objective}>{objective}</li>)}</ul></Objetivos>
    <div className="prose"><p>{item.body}</p></div>
    <Idea><strong>Acción de la misión:</strong> {item.action}</Idea>
    <Cuidado>{item.caution}</Cuidado>
    <Comprueba>Guarda una evidencia concreta: archivo, consulta, captura, log o test. Si no puedes enseñarla, la misión aún no está terminada.</Comprueba>
    <Guardar>Registra fecha, versión de herramientas, dataset usado y qué revisarías antes de pasar a datos reales.</Guardar>
    {lesson === "entorno-reproducible" && <Terminal>{`ia-datos-analitica/\n├── data/incoming/\n├── reports/\n├── src/\n├── tests/\n├── pyproject.toml\n└── README.md`}</Terminal>}
    <ChapterNav next={next && item.next ? { href: `/cursos/ia-datos-analitica/${item.next}`, label: next.title } : undefined} />
  </Chapter>;
}
