import type { EnglishLesson } from "@/lib/english-lessons";

const courseSlug = "ai-consultant";
const courseTitle = "AI Consultant: From Assessment to Production";

export const aiConsultantEnglishLessons: EnglishLesson[] = [
  {
    courseSlug,
    courseTitle,
    slug: "what-an-ai-consultant-does",
    title: "What an AI consultant actually does",
    description: "Start with a business outcome, a baseline and a decision gate instead of selling AI as a vague transformation project.",
    href: "/en/courses/ai-consultant/what-an-ai-consultant-does",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "An AI consultant helps a company decide whether a concrete business problem is worth solving with AI, then designs, tests and operates a solution with accountable people around it. The deliverable is not a chatbot. It is a measurable change in a business process." },
      { type: "h2", text: "The fictional company: Northstar Office Supplies" },
      { type: "p", text: "Northstar has 42 employees. It sells office equipment to local businesses. Sales enquiries arrive by phone, web form and email. Quotes take one to three days, follow-up is inconsistent, and support staff repeatedly search old PDFs for product and warranty answers. The owner asks for “AI everywhere.” Your first job is to turn that into a decision that can be tested." },
      { type: "h2", text: "The operating model" },
      { type: "bullet", text: "Discovery: identify a process, owner, users, constraints and a costly failure." },
      { type: "bullet", text: "Assessment: establish the baseline, data reality, risks and one or more credible opportunities." },
      { type: "bullet", text: "Prototype: test the smallest safe version against representative examples." },
      { type: "bullet", text: "Deployment: define permissions, review, rollback, monitoring and an accountable operator." },
      { type: "bullet", text: "Optimisation: compare results to the baseline and decide whether to expand, change or stop." },
      { type: "h2", text: "A useful first question" },
      { type: "p", text: "Ask: “Which recurring situation loses revenue, creates avoidable delay, or creates unacceptable risk today?” Do not start with “Which model should we use?” A model choice has no meaning until the task, data boundary and success measure are known." },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Write a one-sentence problem statement for Northstar: who experiences the problem, what happens, when it happens and what business outcome is affected. Do not propose a tool yet." },
      { type: "code", text: "Template\n[Role] cannot reliably [complete task] when [trigger occurs].\nThis causes [measurable loss or risk].\nOwner: [named role]. Baseline evidence needed: [record or metric]." },
      { type: "h2", text: "Evidence to save" },
      { type: "p", text: "Save the statement, one unanswered assumption, and the name of the process owner you would interview. This is the first item in your consulting dossier." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "consultant-developer-or-agency",
    title: "Consultant, developer, or automation agency?",
    description: "Choose the role and engagement shape that the client actually needs before promising a build.",
    href: "/en/courses/ai-consultant/consultant-developer-or-agency",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "The same company may need advice, implementation, or an ongoing operated service. Confusing those roles creates vague scopes, hidden dependencies and unhappy clients. Name the role before you name the stack." },
      { type: "h2", text: "Three distinct offers" },
      { type: "bullet", text: "Consulting: diagnose the situation, frame options, quantify trade-offs and recommend a decision. The client may build internally." },
      { type: "bullet", text: "Implementation: build an agreed solution with explicit acceptance criteria, integrations and handover." },
      { type: "bullet", text: "Managed improvement: monitor a working system, review changes, run evaluations and improve a defined workflow over time." },
      { type: "h2", text: "Northstar decision" },
      { type: "p", text: "Northstar has no clean data inventory and no agreed definition of a qualified sales lead. Selling an autonomous follow-up agent today would be irresponsible. A short assessment is the correct first offer because it can establish what exists and whether a safe pilot is worthwhile." },
      { type: "h2", text: "Scope by decision gate" },
      { type: "p", text: "Every engagement should end in a client decision. Examples: approve a paid assessment, approve a contained prototype, pause because the baseline is too weak, or select a non-AI process change. A decision gate protects both the consultant and the client from endless discovery." },
      { type: "code", text: "Initial assessment exit criteria\n- One process map accepted by its owner\n- One baseline metric with a source\n- Data classification and access constraints recorded\n- At least one option compared with a non-AI alternative\n- A written go / change / stop decision" },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "For Northstar, write one sentence explaining why an assessment is a better first engagement than an implementation. Then write the condition that would justify moving to a prototype." },
      { type: "h2", text: "Common failure" },
      { type: "p", text: "Do not call a discovery chat an assessment if it produces no evidence, scope or decision. A friendly conversation is useful; it is not yet a professional deliverable." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "consulting-lifecycle",
    title: "The AI consulting lifecycle",
    description: "Use decision gates from discovery through operation so a pilot cannot quietly become an unsafe production system.",
    href: "/en/courses/ai-consultant/consulting-lifecycle",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "A responsible AI engagement is a sequence of reversible decisions. Each stage answers a different question and produces evidence for the next one. Skipping stages makes the final system look faster only until it fails in production." },
      { type: "h2", text: "Six stages" },
      { type: "bullet", text: "Discover: Is there a material problem with an accountable owner?" },
      { type: "bullet", text: "Assess: What is the baseline, data boundary, risk and plausible opportunity?" },
      { type: "bullet", text: "Design: Which option is proportionate, including a non-AI option?" },
      { type: "bullet", text: "Prototype: Does a contained version meet pre-agreed quality and safety checks?" },
      { type: "bullet", text: "Deploy: Can named people operate, stop and recover the workflow?" },
      { type: "bullet", text: "Improve: Does measured production evidence justify keeping or extending it?" },
      { type: "h2", text: "Northstar example" },
      { type: "p", text: "The first opportunity may be quote preparation. A prototype could draft a quote summary from an approved product catalogue, but it must not price, promise stock, or send an email. A sales employee reviews the draft. The pilot passes only if it reduces preparation time without increasing quotation errors." },
      { type: "h2", text: "Define the stop condition early" },
      { type: "p", text: "Write down what would make you stop. For example: missing product data, insufficient sample cases, a legal restriction, higher error rate, or no measurable benefit. A stop decision is a successful consulting result when it prevents a bad investment." },
      { type: "code", text: "Prototype gate\nInput: approved catalogue + 30 historical, anonymised quote requests\nOutput: draft only; no sending or pricing authority\nPass: reviewer accepts at least the agreed quality threshold\nFail: any unsafe claim, missing citation, or no time improvement\nOwner: Sales operations lead\nRollback: disable the drafting endpoint and retain the prior manual process" },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Choose one Northstar process and write a one-line gate for discovery, assessment and prototype. Each gate must end with a decision, not merely an activity." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "ai-consultant-operating-model",
    title: "Build your AI Consultant Operating Model",
    description: "Create a compact dossier that keeps scope, evidence, owners, risks and decisions together across an engagement.",
    href: "/en/courses/ai-consultant/ai-consultant-operating-model",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "Your operating model is the small set of artefacts you keep for every engagement. It makes your judgement inspectable by the client and makes recurring work possible without relying on memory or a chat transcript." },
      { type: "h2", text: "The consulting dossier" },
      { type: "bullet", text: "Business brief: problem, owner, users, baseline and desired outcome." },
      { type: "bullet", text: "Process map: trigger, inputs, decisions, actions, systems and handoffs." },
      { type: "bullet", text: "Opportunity record: options, non-AI alternative, assumptions, ROI range and decision." },
      { type: "bullet", text: "Risk record: data classes, permissions, failure modes, human approval and rollback." },
      { type: "bullet", text: "Evaluation record: representative cases, expected result, actual result and reviewer." },
      { type: "bullet", text: "Operations record: owner, monitoring, costs, incident path and review date." },
      { type: "h2", text: "Start deliberately small" },
      { type: "p", text: "For the first assessment, a shared document and a spreadsheet can be enough. The discipline matters more than the software. Do not use a CRM, vector database or agent framework merely to make the engagement look advanced." },
      { type: "h2", text: "Northstar dossier starter" },
      { type: "code", text: "Engagement: Northstar quote-response assessment\nSponsor: Managing director\nProcess owner: Sales operations lead\nProblem hypothesis: quote follow-up is delayed and inconsistent\nBaseline needed: request timestamp, first response, quote sent, won/lost\nData boundary: anonymised historical requests only for assessment\nNext gate: approve or reject a paid assessment scope\nReview date: set with the sponsor" },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Create this dossier starter in a local Markdown file. Mark every field you do not know as an assumption. Do not fill gaps with plausible invented numbers." },
      { type: "h2", text: "What you should be able to explain" },
      { type: "p", text: "At the end of this module, you should be able to explain why the business outcome comes first, when an assessment is the right offer, how an engagement advances through gates, and what evidence you need before proposing an AI system." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "read-a-business-before-ai",
    title: "Read a business before proposing AI",
    description: "Build a factual picture of how a company creates value before discussing models, agents, or automation.",
    href: "/en/courses/ai-consultant/read-a-business-before-ai",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "A company is not its software list. Before suggesting AI, understand how it earns revenue, serves customers, fulfils work and learns from failure. You are looking for facts, not a polished story about innovation." },
      { type: "h2", text: "The five questions" },
      { type: "bullet", text: "Who pays, for what outcome, and how is that value delivered?" },
      { type: "bullet", text: "How does a new customer move from first contact to paid work?" },
      { type: "bullet", text: "Where do people wait, repeat work, re-enter information or make judgement calls?" },
      { type: "bullet", text: "Which systems hold the records needed to understand the process?" },
      { type: "bullet", text: "Who owns the process and can approve a change?" },
      { type: "h2", text: "Northstar business snapshot" },
      { type: "p", text: "Northstar receives leads through a web form, phone and email. A sales coordinator copies the request into the CRM, asks suppliers about availability, then prepares a quote. The customer may wait two days. A salesperson follows up when they remember. This is a business narrative; it still needs records before it becomes a diagnosis." },
      { type: "h2", text: "Do not confuse a symptom with a process" },
      { type: "p", text: "“Our team is overloaded” is a symptom. “Quote requests are copied from inbox to CRM, then wait for stock confirmation before a salesperson sends a price” describes a process you can inspect. Start with the smallest process that connects to money, quality or material risk." },
      { type: "code", text: "Business reading note\nCustomer outcome: ____________________\nTrigger: _____________________________\nFirst human owner: ___________________\nSystems involved: ____________________\nDecision points: _____________________\nEvidence available: __________________\nUnknowns: ____________________________" },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Fill this note for Northstar's quote process. Mark any detail you cannot prove as unknown. A good assessment begins by protecting uncertainty instead of hiding it." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "revenue-customers-and-constraints",
    title: "Revenue, customers, and operating constraints",
    description: "Connect a process to the customer promise, economic model, and constraints that shape a viable AI solution.",
    href: "/en/courses/ai-consultant/revenue-customers-and-constraints",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "An AI proposal can be technically sound and commercially wrong. The same delay means different things in a low-margin catalogue business, a high-value B2B sale, and an emergency service. Learn the economics and customer expectation before measuring automation." },
      { type: "h2", text: "Map the customer promise" },
      { type: "p", text: "Ask what the customer expects at each stage: a quick response, an accurate quote, a confirmed delivery date, a knowledgeable answer, or a human escalation. An AI workflow must protect that promise. Faster but less reliable is often a regression." },
      { type: "h2", text: "Northstar constraints" },
      { type: "bullet", text: "Prices and stock change, so a model cannot invent or autonomously confirm either." },
      { type: "bullet", text: "Some quote requests include contact details and past order information, so assessment data must be minimised and access controlled." },
      { type: "bullet", text: "Sales staff remain responsible for commercial promises, even if a system drafts a response." },
      { type: "bullet", text: "The company has only one part-time CRM administrator, so any pilot must be simple to operate." },
      { type: "h2", text: "Constraint is a design input" },
      { type: "p", text: "A constraint is not a nuisance to work around later. It selects the solution. If stock is authoritative only in an ERP, a drafting assistant should cite the ERP record or abstain. If no reliable data exists, process work may be a better investment than an LLM." },
      { type: "code", text: "Opportunity constraint record\nCustomer promise at risk: _____________\nCommercial authority: _________________\nAuthoritative system of record: ________\nPersonal or sensitive data: ____________\nHuman approval required: ______________\nOperational constraint: ________________\nNon-AI alternative: ___________________" },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Create the constraint record for Northstar. State one action the future prototype must never take without human approval." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "knowledge-flows-and-handoffs",
    title: "Knowledge flows, handoffs, and information loss",
    description: "Locate where information changes hands, disappears, or becomes unreliable inside a real business workflow.",
    href: "/en/courses/ai-consultant/knowledge-flows-and-handoffs",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "Many promising AI opportunities are actually information-flow failures. A lead is not followed up because the CRM is incomplete. A support reply is slow because the current policy lives in an inbox. Map the handoff before building retrieval or automation." },
      { type: "h2", text: "Trace the information, not just the people" },
      { type: "bullet", text: "What arrives at the trigger: form fields, email text, call note, file or message?" },
      { type: "bullet", text: "What is copied, transformed, summarised, approved or discarded?" },
      { type: "bullet", text: "Where is the authoritative record after each handoff?" },
      { type: "bullet", text: "What information does the next person need but fail to receive?" },
      { type: "h2", text: "Northstar handoff" },
      { type: "p", text: "A customer emails a product list. The coordinator creates a CRM note, but attachments and urgency are not consistently recorded. A salesperson searches prior quotes and supplier emails. When stock is unavailable, the reason may stay in a personal mailbox. The next follow-up has no reliable context." },
      { type: "h2", text: "AI is not the first fix for every handoff" },
      { type: "p", text: "A required CRM field, a shared queue, or a better ownership rule can outperform a model. Your professional value comes from comparing those options honestly. Use AI only where it adds a capability such as extracting structured details, summarising approved evidence, or drafting a reviewable response." },
      { type: "code", text: "Handoff map\nTrigger -> input -> owner -> system of record -> decision -> next owner\n\nExample\nEmail request -> attachment + text -> coordinator -> CRM -> qualify? -> sales\nMissing information: urgency, attachment metadata, prior customer context\nFailure effect: delayed or inconsistent quote follow-up" },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Draw Northstar's quote-request handoff in six nodes. Circle one missing datum and write one non-AI repair before proposing an AI capability." },
    ],
  },
  {
    courseSlug,
    courseTitle,
    slug: "sipoc-and-value-stream-mapping",
    title: "SIPOC and value-stream mapping",
    description: "Use lightweight process maps to turn a vague AI request into an inspectable workflow and baseline.",
    href: "/en/courses/ai-consultant/sipoc-and-value-stream-mapping",
    alternateRoute: null,
    blocks: [
      { type: "p", text: "You do not need elaborate notation to improve a small-business process. SIPOC and a simple value-stream view give you enough structure to ask useful questions and find where waiting, rework or risky judgement occurs." },
      { type: "h2", text: "SIPOC in plain language" },
      { type: "bullet", text: "Suppliers: who or what provides the input?" },
      { type: "bullet", text: "Inputs: what record, request, file or signal starts the work?" },
      { type: "bullet", text: "Process: what repeatable steps turn that input into an outcome?" },
      { type: "bullet", text: "Outputs: what is produced, recorded or promised?" },
      { type: "bullet", text: "Customers: who receives the outcome or depends on it next?" },
      { type: "h2", text: "Northstar SIPOC starter" },
      { type: "code", text: "Suppliers: prospect, existing customer, website, phone system\nInputs: request text, product list, customer identity\nProcess: capture -> qualify -> check stock -> draft quote -> review -> send -> follow up\nOutputs: quote, decline, clarification request, CRM record\nCustomers: buyer, sales manager, fulfilment team" },
      { type: "h2", text: "Add elapsed time and failure points" },
      { type: "p", text: "A value-stream map adds time: how long work waits, how long a person actually works, and where it returns for correction. Write measured time separately from guesses. The difference between the two often becomes your first assessment deliverable." },
      { type: "h2", text: "Practical mission" },
      { type: "p", text: "Create Northstar's SIPOC. Then add three columns: evidence source, current elapsed time, and failure if the step is wrong. Do not estimate revenue impact yet; that is the next module." },
      { type: "h2", text: "Evidence to save" },
      { type: "p", text: "Save the map with unknowns visible. It becomes the shared reference for the process owner, the technical reviewer and the client sponsor." },
    ],
  },
];
