import type { EnglishLesson } from "@/lib/english-lessons";

export const ollamaContextWindowLesson: EnglishLesson = {
  courseSlug: "ia-local",
  courseTitle: "Claude Code + Local AI",
  slug: "ollama-context-window-32k",
  title: "Ollama Caps Context at 4K or 32K? Check What It Actually Loaded",
  heading: "Ollama Using 4K or 32K Context Instead of 256K? How to Check",
  description: "Ollama often allocates 4096 or 32768 tokens even when a model card lists 128K–256K. Check `ollama ps` for CONTEXT and PROCESSOR, then raise the window without spilling onto CPU.",
  href: "/en/courses/ia-local/ollama-context-window-32k",
  alternateRoute: null,
  blocks: [
    { type: "p", text: "The model card may list 128K or 256K. That is not proof that the running Ollama instance reserved that many tokens." },
    { type: "p", text: "Ollama can allocate a context window based on server defaults, app settings, or request/model configuration. This guide checks the window that is actually loaded (CONTEXT) and whether the model stayed on the GPU (PROCESSOR), then changes only the setting that the running server actually honors." },
    { type: "p", text: "If the input exceeds the allocated context window, Ollama or the client may truncate, compact, or discard earlier context depending on the runtime and client path. Verify the actual allocated context and inspect the logs rather than assuming the model-card maximum is active." },
    { type: "p", text: "If `ollama ps` shows `100% CPU` even with a small context window, stop here and use the dedicated GPU troubleshooting lesson. This article does not diagnose basic GPU detection." },
    { type: "link", text: "Ollama Not Using GPU on Windows", href: "/en/courses/ia-local/ollama-gpu-windows" },
    { type: "link", text: "Fix Ollama Errors", href: "/en/courses/ia-local/troubleshooting-ollama" },
    { type: "link", text: "Connect Claude Code to Your Local AI", href: "/en/courses/ia-local/conectar-ollama" },

    { type: "h2", text: "Quick diagnosis" },
    { type: "p", text: "Use the model the same way you normally do: CLI, API, or coding agent. Then inspect the loaded runner." },
    { type: "h3", text: "Command" },
    { type: "code", text: "ollama ps" },
    { type: "h3", text: "Expected result" },
    { type: "p", text: "A row for the loaded model. On current Ollama versions, look especially for CONTEXT and PROCESSOR." },
    { type: "code", text: "NAME             ID              SIZE      PROCESSOR    CONTEXT    UNTIL\nmodel:latest     ...             ...       100% GPU     32768      ..." },
    { type: "p", text: "Do not depend on exact SIZE values for the diagnosis." },
    { type: "h3", text: "Decision" },
    { type: "bullet", text: "Empty output: the model is not currently loaded. Send one short request, then run `ollama ps` again." },
    { type: "bullet", text: "No CONTEXT column: check `ollama --version` and make sure you are inspecting the same Ollama server that handles the request." },
    { type: "bullet", text: "CONTEXT is 4096 or 32768 and the workload needs 64K or more: go to Cause 1." },
    { type: "bullet", text: "CONTEXT remains at the server default after changing a client-side setting: go to Cause 2." },
    { type: "bullet", text: "CONTEXT is large and PROCESSOR becomes 100% CPU or a CPU/GPU split: go to Cause 3." },
    { type: "bullet", text: "CONTEXT matches the intended value and PROCESSOR remains 100% GPU, but early instructions or files disappear on large prompts: go to Cause 4." },
    { type: "bullet", text: "PROCESSOR is already 100% CPU with a small 4K/8K context: this is probably a GPU detection/offload problem, not a context problem." },
    { type: "p", text: "The central diagnostic loop is:" },
    { type: "code", text: "ollama ps\n    ↓\nCONTEXT\nWhat window is actually allocated?\n    ↓\nPROCESSOR\nDid the model remain on GPU?" },

    { type: "h2", text: "Why Ollama's own documentation appears to disagree" },
    { type: "p", text: "Two official Ollama documentation pages currently describe the unconfigured default differently. The context-length page documents VRAM-based defaults: less than 24 GiB uses 4K, 24–48 GiB uses 32K, and 48 GiB or more uses 256K. It recommends at least 64000 tokens for web search, agents, and coding tools. The FAQ also states a 4096-token default." },
    { type: "p", text: "Because behavior can vary by Ollama version, detected VRAM, app settings, and how the server was started, do not infer the active context size from documentation alone. The operational source of truth is the CONTEXT value shown by the runner serving the request." },
    { type: "code", text: "ollama ps" },

    { type: "h2", text: "Collect evidence before changing anything" },
    { type: "p", text: "Collect three facts: the advertised model context, the allocated CONTEXT, and the current PROCESSOR split." },
    { type: "h3", text: "Advertised model context" },
    { type: "code", text: "ollama show MODEL" },
    { type: "p", text: "Replace MODEL with the tag you actually use. Some models expose context information in their metadata. Treat this as the model's advertised or trained capability, not proof that the runtime allocated that window." },
    { type: "h3", text: "Allocated runtime window" },
    { type: "code", text: "ollama ps" },
    { type: "bullet", text: "CONTEXT: the context allocated to the running model." },
    { type: "bullet", text: "PROCESSOR: whether execution is on GPU, CPU, or split." },
    { type: "h3", text: "Logs" },
    { type: "p", text: "Use logs only as supporting evidence. Ollama's output and warning wording can vary between releases." },
    { type: "p", text: "Windows: open the current server log under:" },
    { type: "code", text: "%LOCALAPPDATA%\\Ollama" },
    { type: "p", text: "macOS:" },
    { type: "code", text: "tail -n 200 ~/.ollama/logs/server.log" },
    { type: "p", text: "Linux with systemd:" },
    { type: "code", text: "journalctl -u ollama --no-pager -n 200" },
    { type: "p", text: "Use logs to identify which server started, configuration applied at startup, GPU offload behavior, and prompt-limit warnings when present. The absence of a particular warning is not proof that the advertised model context is active." },

    { type: "h2", text: "Cause 1: Ollama applied a smaller default context" },
    { type: "h3", text: "What this means" },
    { type: "p", text: "The maximum context advertised by a model is not necessarily the context allocated by the Ollama server. A model capable of 128K or 256K may be running with CONTEXT 4096 or CONTEXT 32768, depending on the version, configuration, and available resources." },
    { type: "h3", text: "Check" },
    { type: "code", text: "ollama ps" },
    { type: "h3", text: "Expected result" },
    { type: "p", text: "CONTEXT is smaller than the context required by the workload. Current Ollama guidance recommends at least 64000 tokens for agent and coding workloads when resources allow." },
    { type: "h3", text: "Fix: Ollama app" },
    { type: "p", text: "Use the context-length slider in Ollama settings. Restart the app after changing a server-level setting when required by the installed version." },
    { type: "h3", text: "Fix: foreground server on macOS or Linux" },
    { type: "code", text: "OLLAMA_CONTEXT_LENGTH=64000 ollama serve" },
    { type: "p", text: "This is macOS/Linux-style shell syntax. It only affects requests if this process is the Ollama server actually listening on port 11434. Do not start a second server and assume clients are using it." },
    { type: "h3", text: "Fix: Linux systemd" },
    { type: "code", text: "sudo systemctl edit ollama.service" },
    { type: "p", text: "Add:" },
    { type: "code", text: "[Service]\nEnvironment=\"OLLAMA_CONTEXT_LENGTH=64000\"" },
    { type: "p", text: "Then reload the service configuration and restart the actual server:" },
    { type: "code", text: "sudo systemctl daemon-reload\nsudo systemctl restart ollama" },
    { type: "h3", text: "Fix: macOS application environment" },
    { type: "code", text: "launchctl setenv OLLAMA_CONTEXT_LENGTH 64000" },
    { type: "p", text: "Quit and reopen the Ollama app. Do not assume this survives a reboot without a separately configured persistent launch environment." },
    { type: "h3", text: "Fix: Windows" },
    { type: "bullet", text: "Quit Ollama from the taskbar or system tray." },
    { type: "bullet", text: "Open Edit environment variables for your account." },
    { type: "bullet", text: "Create or edit OLLAMA_CONTEXT_LENGTH with the value 64000." },
    { type: "bullet", text: "Start Ollama again from the Start menu." },
    { type: "h3", text: "Interactive Ollama session" },
    { type: "code", text: "/set parameter num_ctx 64000" },
    { type: "p", text: "This changes the interactive model/session behavior; it does not change every client or daemon default." },
    { type: "h3", text: "Native Ollama API" },
    { type: "code", text: "curl http://localhost:11434/api/generate -d '{\n  \"model\": \"MODEL\",\n  \"prompt\": \"Reply with ok.\",\n  \"options\": {\n    \"num_ctx\": 64000\n  }\n}'" },
    { type: "h3", text: "Verify" },
    { type: "code", text: "ollama ps" },
    { type: "p", text: "Confirm that CONTEXT equals the intended value, then inspect PROCESSOR. If CONTEXT did not change, verify which process owns port 11434." },
    { type: "p", text: "Linux:" },
    { type: "code", text: "ss -ltnp | grep 11434" },
    { type: "p", text: "Windows:" },
    { type: "code", text: "netstat -ano | findstr 11434" },

    { type: "h2", text: "Why you cannot set Ollama context size through the OpenAI-compatible API" },
    { type: "p", text: "Ollama exposes several configuration paths, but they are not interchangeable. The native Ollama API accepts options.num_ctx; the server can use OLLAMA_CONTEXT_LENGTH; the app exposes a context setting; and ollama run supports /set parameter num_ctx." },
    { type: "p", text: "The OpenAI API does not define a model context-size parameter equivalent to Ollama's num_ctx. A client using /v1/chat/completions therefore cannot assume that a client-side context-size field changed Ollama's allocation." },
    { type: "p", text: "For a stable per-model setting behind the OpenAI-compatible endpoint, create a Modelfile:" },
    { type: "code", text: "FROM MODEL\nPARAMETER num_ctx 64000" },
    { type: "code", text: "ollama create model-64k -f Modelfile" },
    { type: "p", text: "Point the client at model-64k, run a request, and verify again with `ollama ps`." },
    { type: "link", text: "Official Ollama OpenAI compatibility documentation", href: "https://docs.ollama.com/api/openai-compatibility", external: true },

    { type: "h2", text: "Cause 2: The client never changed num_ctx" },
    { type: "h3", text: "What this means" },
    { type: "p", text: "The server is still using its default. This can happen when the client uses an OpenAI-compatible endpoint, exposes a context UI that does not control Ollama's allocation, talks to another instance, or the expected server was not restarted." },
    { type: "h3", text: "Check" },
    { type: "code", text: "ollama ps" },
    { type: "h3", text: "Expected result" },
    { type: "p", text: "CONTEXT remains at the server default rather than the value expected from the client configuration." },
    { type: "h3", text: "Fix" },
    { type: "p", text: "Prefer OLLAMA_CONTEXT_LENGTH or the Ollama app setting. For a stable per-model configuration, use a Modelfile with PARAMETER num_ctx 64000." },
    { type: "h3", text: "Verify" },
    { type: "p", text: "Start the actual client or agent, run a request, then inspect NAME, CONTEXT, and PROCESSOR with `ollama ps`. Do not trust only the client's settings screen." },

    { type: "h2", text: "Cause 3: Increasing context caused CPU/GPU offload" },
    { type: "h3", text: "What this means" },
    { type: "p", text: "A larger context needs more memory, particularly for the KV cache. Increasing context can turn PROCESSOR from 100% GPU into a CPU/GPU split. The model may still run, but performance can fall dramatically." },
    { type: "h3", text: "Check" },
    { type: "p", text: "Run `ollama ps` before and after increasing context. Record both CONTEXT and PROCESSOR." },
    { type: "h3", text: "Expected result" },
    { type: "p", text: "If the larger context no longer fits efficiently in VRAM, PROCESSOR may cease to show 100% GPU." },
    { type: "h3", text: "Fix" },
    { type: "p", text: "Do not immediately reduce an agent or coding workload to 32K without considering alternatives. If 64K causes CPU offload, reduce unnecessary parallelism, consider a smaller model or weight quantization, and consider KV-cache quantization where supported." },
    { type: "p", text: "For a single workload, reducing parallelism may help. Adapt this service setting to the actual way Ollama is launched:" },
    { type: "code", text: "[Service]\nEnvironment=\"OLLAMA_NUM_PARALLEL=1\"" },
    { type: "h3", text: "KV-cache quantization" },
    { type: "bullet", text: "f16: highest KV-cache memory requirement and default precision." },
    { type: "bullet", text: "q8_0: about half the f16 KV-cache memory in current Ollama documentation, with a small precision trade-off." },
    { type: "bullet", text: "q4_0: about one quarter of f16 KV-cache memory, with a greater possible quality trade-off." },
    { type: "p", text: "KV-cache quantization requires Flash Attention and is currently server-wide. Confirm support for the active backend and model before enabling it." },
    { type: "code", text: "OLLAMA_FLASH_ATTENTION=1\nOLLAMA_KV_CACHE_TYPE=q8_0" },
    { type: "p", text: "Set these in the environment format appropriate to the server, then restart that server. Do not set 256K merely because the model advertises 256K if it causes significant CPU offload." },
    { type: "h3", text: "What if 64K still does not fit?" },
    { type: "p", text: "32K is possible, but coding agents and tool-heavy workloads may lose useful working context below Ollama's recommended 64K. Do not treat 32K as equivalent to 64K." },
    { type: "h3", text: "Verify" },
    { type: "code", text: "ollama ps" },
    { type: "p", text: "The goal is sufficient CONTEXT for the workload while keeping PROCESSOR at 100% GPU. If the system cannot satisfy both, make the trade-off explicit. If it remains 100% CPU after returning to a small context, use the GPU troubleshooting lesson." },

    { type: "h2", text: "Cause 4: The working set exceeds the allocated context" },
    { type: "h3", text: "What this means" },
    { type: "p", text: "The effective working set can include system instructions, conversation history, user prompts, files, repository context, tool schemas, MCP definitions, and tool results. If these exceed CONTEXT, not all information can remain available. Exact truncation or compaction depends on the client and API path." },
    { type: "h3", text: "Check" },
    { type: "p", text: "Compare the CONTEXT shown by `ollama ps` with the material the client is attempting to keep active. Inspect server and client logs when available." },
    { type: "h3", text: "Expected result" },
    { type: "p", text: "The model may still return a fluent answer while failing to preserve earlier instructions or files because the allocated context is smaller than the working set." },
    { type: "h3", text: "Fix" },
    { type: "bullet", text: "Increase context using Cause 1 when VRAM allows." },
    { type: "bullet", text: "Use Cause 3 if the increase causes CPU offload." },
    { type: "bullet", text: "Start a fresh session and remove unused tools or MCP servers." },
    { type: "bullet", text: "Shorten oversized instruction files and avoid repeatedly injecting irrelevant repository data." },
    { type: "h3", text: "Verify" },
    { type: "p", text: "Repeat a task that depends on an instruction placed early in the context, then inspect `ollama ps`. If it behaves correctly with a larger verified CONTEXT, the earlier allocation was insufficient for that working set. This does not prove one universal truncation mechanism." },

    { type: "h2", text: "Safety" },
    { type: "bullet", text: "Restarting Ollama unloads models from memory. It does not delete the model." },
    { type: "bullet", text: "Do not set OLLAMA_HOST=0.0.0.0:11434 to solve a context problem. It exposes the service to the network and is unrelated to num_ctx." },
    { type: "bullet", text: "Debug logging can significantly increase log volume. Disable it after diagnosis." },
    { type: "bullet", text: "OLLAMA_KV_CACHE_TYPE and Flash Attention configuration can affect all models served by that Ollama process." },
    { type: "bullet", text: "Do not modify GPU drivers, firewall settings, or CUDA_VISIBLE_DEVICES as part of this context troubleshooting flow." },

    { type: "h2", text: "If it still doesn't work" },
    { type: "bullet", text: "CONTEXT does not change after setting OLLAMA_CONTEXT_LENGTH: confirm that you restarted the process that actually owns port 11434. It may be the desktop app, foreground server, systemd, Docker, WSL, or native Windows service." },
    { type: "bullet", text: "CONTEXT increases but PROCESSOR leaves 100% GPU: the increase probably exceeded the efficient GPU memory budget. Use Cause 3." },
    { type: "bullet", text: "CONTEXT is correct and fully on GPU but a coding harness assumes another size: inspect the client's own compaction and context assumptions." },
    { type: "bullet", text: "Windows-native and WSL Ollama are both installed: make sure `ollama ps` reaches the same environment the client calls." },
    { type: "p", text: "Do not reinstall Ollama merely to change a context configuration." },

    { type: "h2", text: "Primary sources" },
    { type: "link", text: "Ollama — Context length", href: "https://docs.ollama.com/context-length", external: true },
    { type: "link", text: "Ollama — FAQ", href: "https://docs.ollama.com/faq", external: true },
    { type: "link", text: "Ollama — OpenAI compatibility", href: "https://docs.ollama.com/api/openai-compatibility", external: true },
    { type: "link", text: "Ollama — Modelfile", href: "https://docs.ollama.com/modelfile", external: true },
    { type: "link", text: "Ollama — Troubleshooting", href: "https://docs.ollama.com/troubleshooting", external: true },
    { type: "link", text: "Ollama — Linux", href: "https://docs.ollama.com/linux", external: true },
    { type: "link", text: "Ollama — Windows", href: "https://docs.ollama.com/windows", external: true },
    { type: "link", text: "Ollama — Claude Code integration", href: "https://docs.ollama.com/integrations/claude-code", external: true },
    { type: "p", text: "Last reviewed: 30 August 2026." },
  ],
};
