export type SearchItem = {
  href: string;
  title: string;
  section: string;
  keywords: string;
};

export const searchData: SearchItem[] = [
  { href: "/guia", title: "Inicio de la guía", section: "Empezar", keywords: "home portada qué es claude code introducción" },
  { href: "/", title: "Aulafy", section: "Cursos", keywords: "aulafy portada cursos ia inteligencia artificial open source" },
  { href: "/instalacion", title: "Instalación", section: "Empezar", keywords: "instalar npm node api key macos windows wsl linux setup actualizar" },
  { href: "/primeros-pasos", title: "Primeros pasos", section: "Empezar", keywords: "iniciar sesión modo auto plan primera vez interfaz prompt print headless" },
  { href: "/donde-usar", title: "CLI, app y móvil", section: "Empezar", keywords: "cli terminal app escritorio desktop web navegador vs code jetbrains ide móvil movil ios remote control dispatch teleport channels slack superficies diferencias" },
  { href: "/recetas", title: "Recetas prácticas", section: "Práctica diaria", keywords: "ejemplos prompts copiar aprender crear errores git datos automatizar terminal documentar día a día" },
  { href: "/proyectos", title: "Proyectos guiados", section: "Práctica diaria", keywords: "web personal app tareas to-do script python paso a paso tutorial construir proyecto" },
  { href: "/prompts", title: "Escribir buenos prompts", section: "Práctica diaria", keywords: "prompt engineering específico contexto plantillas antes después comunicar pedir" },
  { href: "/glosario", title: "Glosario", section: "Práctica diaria", keywords: "términos diccionario api commit backend frontend repositorio stack trace mcp deploy localhost json definiciones" },
  { href: "/skills", title: "Skills", section: "Extender", keywords: "agent skills skill.md frontmatter reutilizable comandos personalizados automatizar invocación" },
  { href: "/subagentes", title: "Subagentes", section: "Extender", keywords: "agentes paralelo .claude/agents revisor depurador delegar background especializado tools model" },
  { href: "/plugins", title: "Plugins", section: "Extender", keywords: "marketplace instalar bundle plugin install anthropics extensiones paquetes" },
  { href: "/flujos", title: "Flujos de trabajo pro", section: "Extender", keywords: "plan mode rewind checkpoint background output styles deshacer shift tab esc trucos mejores prácticas" },
  { href: "/comandos", title: "Comandos", section: "Referencia", keywords: "slash commands flags cli atajos teclado modelos opus sonnet haiku fable help clear doctor compact" },
  { href: "/configuracion", title: "Configuración", section: "Referencia", keywords: "settings.json claude.md memoria variables entorno modelo vscode jetbrains proxy perfiles" },
  { href: "/mcp", title: "Servidores MCP", section: "Referencia", keywords: "model context protocol postgres github puppeteer base datos navegador api herramientas externas" },
  { href: "/hooks", title: "Hooks", section: "Referencia", keywords: "pretoolcall posttoolcall stop automatizar prettier tests log bloquear matcher eventos" },
  { href: "/permisos", title: "Permisos", section: "Referencia", keywords: "allow deny seguridad confirmación dangerously skip permissions herramientas control" },
  { href: "/avanzado", title: "Uso avanzado", section: "Referencia", keywords: "subagentes worktree headless ci cd fast compact resume tmux git productividad" },
  { href: "/faq", title: "Preguntas frecuentes", section: "Ayuda", keywords: "precio coste seguridad privacidad reemplaza programadores modelo lenguajes dudas faq" },
  { href: "/problemas", title: "Solución de problemas", section: "Ayuda", keywords: "error command not found eacces node api key rate limit lento doctor troubleshooting arreglar" },
  { href: "/recursos", title: "Recursos", section: "Ayuda", keywords: "enlaces links docs documentación oficial repos skills mcp cursos youtube tutoriales x twitter comunidad" },
  { href: "/comparativa", title: "Comparativa", section: "Ayuda", keywords: "comparación versus cursor windsurf copilot chatgpt diferencias elegir herramientas" },
  { href: "/pymes", title: "Pymes y oficina", section: "Según tu perfil", keywords: "empresa negocio autónomo oficina excel csv facturas documentos informes automatizar tareas ahorrar tiempo no programador productividad datos" },
  { href: "/equipos", title: "Perfiles técnicos", section: "Según tu perfil", keywords: "equipos developers code review refactor testing tdd ci cd headless monorepo estandarizar plugin interno mcp integraciones avanzado" },
  { href: "/volumen-2", title: "Claude Code + IA Local", section: "Volumen II", keywords: "volumen dos ia local ollama lm studio apps locales" },
  { href: "/volumen-2/terminal", title: "La terminal sin miedo", section: "Volumen II", keywords: "cli terminal comandos pwd ls cd" },
  { href: "/volumen-2/proyectos", title: "Cómo trabajar con tus proyectos", section: "Volumen II", keywords: "carpetas proyectos npm install dev guardar reabrir" },
  { href: "/volumen-2/prompts", title: "Escribir buenos encargos", section: "Volumen II", keywords: "prompts encargos requisitos pedir aplicaciones" },
  { href: "/volumen-2/ia-local", title: "IA local", section: "Volumen II", keywords: "ollama lm studio qwen gemma phi modelos locales privado" },
  { href: "/volumen-2/depurar", title: "Depurar y proteger", section: "Volumen II", keywords: "errores git claves seguridad backups" },
  { href: "/volumen-2/chatbot-legal", title: "Chatbot legal RAG", section: "Volumen II", keywords: "rag documentos legales citar ley privacidad rgpd" },
  { href: "/volumen-2/pdf", title: "Pregunta a tus PDF", section: "Volumen II", keywords: "pdf rag documentos paginas citas ocr" },
  { href: "/volumen-2/voz", title: "Chatbot con voz", section: "Volumen II", keywords: "voz stt tts microfono moonshine kokoro" },
  { href: "/volumen-2/texto-a-audio", title: "Texto a audio", section: "Volumen II", keywords: "tts audio mp3 kokoro magpie f5" },
  { href: "/volumen-2/simulaciones-3d", title: "Simulaciones 3D", section: "Volumen II", keywords: "threejs 3d sistema solar orbitcontrols clases" },
  { href: "/volumen-2/avatar", title: "Avatar que habla", section: "Volumen II", keywords: "avatar lip sync visemas cursos video" },
  { href: "/volumen-2/wordpress", title: "Tema de WordPress", section: "Volumen II", keywords: "wordpress tema bloques full site editing theme json" },
  { href: "/volumen-2/landing", title: "Web en minutos", section: "Volumen II", keywords: "landing web servicio publicar formulario" },
  { href: "/volumen-2/facturacion", title: "Asistente para autónomos", section: "Volumen II", keywords: "facturas autonomos oficina contabilidad" },
  { href: "/volumen-2/estudio", title: "App para estudiar", section: "Volumen II", keywords: "estudiar apuntes examenes preguntas flashcards" },
  { href: "/volumen-2/publicar", title: "Publicar en la red", section: "Volumen II", keywords: "deploy publicar vercel internet dominio" },
  { href: "/volumen-2/cluster", title: "Clúster casero", section: "Volumen II", keywords: "exo cluster ordenadores red modelos grandes" },
  { href: "/cursos/ia-generativa", title: "IA generativa: imagen, voz y vídeo", section: "IA generativa", keywords: "comfyui flux diffusers whisper piper wan imagen voz video open source" },
  { href: "/cursos/ia-generativa/mapa-licencias", title: "Mapa de herramientas y licencias", section: "IA generativa", keywords: "licencias modelos abiertos flux schnell dev apache no comercial" },
  { href: "/cursos/ia-generativa/comfyui-flux", title: "ComfyUI + FLUX desde cero", section: "IA generativa", keywords: "comfyui flux workflow imagenes generativas nodos seed" },
  { href: "/cursos/ia-generativa/diffusers-python", title: "Diffusers con Python reproducible", section: "IA generativa", keywords: "hugging face diffusers fluxpipeline python seed manifest" },
  { href: "/cursos/ia-generativa/control-lora", title: "Control, referencias y LoRA", section: "IA generativa", keywords: "lora controlnet inpainting referencias visuales consistencia" },
  { href: "/cursos/ia-generativa/voz-local", title: "Voz local: Whisper y Piper", section: "IA generativa", keywords: "whisper piper tts stt subtitulos audio voz local" },
  { href: "/cursos/ia-generativa/video-local", title: "Vídeo local con Wan y ComfyUI", section: "IA generativa", keywords: "wan video local comfyui text to video imagen a video ffmpeg" },
  { href: "/cursos/ia-generativa/proyecto-multimodal", title: "Proyecto: cápsula educativa multimedia", section: "IA generativa", keywords: "capsula educativa multimedia manifest guion subtitulos video" },
  { href: "/aviso-legal", title: "Aviso legal", section: "Legal", keywords: "aviso legal titular responsable contacto lssi condiciones uso" },
  { href: "/licencia", title: "Licencia", section: "Legal", keywords: "cc by mit contenido codigo reutilizar" },
  { href: "/privacidad", title: "Privacidad", section: "Legal", keywords: "privacidad cookies chat groq datos ip" },
  { href: "/cookies", title: "Cookies", section: "Legal", keywords: "cookies localstorage modo claro oscuro sin analitica publicidad seguimiento" },
];
