export type SearchItem = {
  href: string;
  title: string;
  section: string;
  keywords: string;
};

export const searchData: SearchItem[] = [
  { href: "/cursos/codex-desde-cero", title: "Codex desde cero", section: "Codex desde cero", keywords: "codex principiantes cero archivos automatizar proyectos curso general manual pdf" },
  { href: "/cursos/codex-desde-cero/que-es-codex", title: "Qué es Codex y qué no es", section: "Codex desde cero", keywords: "codex chat work elegir herramienta agente ia" },
  { href: "/cursos/codex-desde-cero/donde-usar-codex", title: "Dónde utilizar Codex: app, web, CLI e IDE", section: "Codex desde cero", keywords: "codex app web cli ide mac windows linux superficies" },
  { href: "/cursos/codex-desde-cero/instalacion", title: "Instala e inicia sesión en tu plataforma", section: "Codex desde cero", keywords: "instalar codex iniciar sesion chatgpt mac windows linux" },
  { href: "/cursos/codex-desde-cero/primera-carpeta", title: "Crea una carpeta de práctica y empieza en solo lectura", section: "Codex desde cero", keywords: "carpeta practica solo lectura seguridad inspeccionar archivos" },
  { href: "/cursos/codex-desde-cero/pedir-resultados-claros", title: "Pide resultados claros sin aprender prompt engineering", section: "Codex desde cero", keywords: "prompts encargos claros resultado verificar lenguaje natural" },
  { href: "/cursos/codex-desde-cero/planificar-verificar", title: "Planifica, corrige el rumbo y cierra con evidencia", section: "Codex desde cero", keywords: "planificar corregir rumbo terminado evidencia comprobaciones" },
  { href: "/cursos/codex-desde-cero/organizar-archivos", title: "Organiza archivos sin perder los originales", section: "Codex desde cero", keywords: "organizar archivos inventario vista previa copias no sobrescribir" },
  { href: "/cursos/codex-desde-cero/crear-documentos-datos-presentaciones", title: "Crea documentos, datos, presentaciones, PDF e imágenes", section: "Codex desde cero", keywords: "documentos hojas calculo presentaciones pdf imagenes work entregables" },
  { href: "/cursos/codex-desde-cero/investigar-web", title: "Investiga en la web y utiliza el navegador con criterio", section: "Codex desde cero", keywords: "investigar web browser fuentes citas fechas navegador" },
  { href: "/cursos/codex-desde-cero/computer-use-seguro", title: "Usa Computer Use sin entregar el control de tu equipo", section: "Codex desde cero", keywords: "computer use aplicaciones escritorio permisos acciones externas seguridad" },
  { href: "/cursos/codex-desde-cero/primera-web-local", title: "Construye tu primera web local", section: "Codex desde cero", keywords: "crear web local sin programar html css revisar proyecto" },
  { href: "/cursos/codex-desde-cero/automatizar-con-vista-previa", title: "Automatiza una tarea repetitiva con vista previa", section: "Codex desde cero", keywords: "automatizar tarea vista previa dry run csv recuperar errores" },
  { href: "/cursos/codex-desde-cero/proyectos-tareas-entornos", title: "Organiza proyectos, tareas y entornos", section: "Codex desde cero", keywords: "proyectos tareas chat local worktree cloud contexto" },
  { href: "/cursos/codex-desde-cero/permisos-privacidad-secretos", title: "Permisos, privacidad, secretos y acciones externas", section: "Codex desde cero", keywords: "permisos privacidad secretos claves prompt injection acciones externas" },
  { href: "/cursos/codex-desde-cero/copias-seguridad-git", title: "Copias de seguridad y Git sin miedo", section: "Codex desde cero", keywords: "backup copias git status diff deshacer cambios" },
  { href: "/cursos/codex-desde-cero/instrucciones-agents-md", title: "Instrucciones personales y AGENTS.md", section: "Codex desde cero", keywords: "instrucciones personales agents md reglas proyecto verificacion" },
  { href: "/cursos/codex-desde-cero/skills-plugins-mcp", title: "Elige entre skills, plugins y MCP", section: "Codex desde cero", keywords: "skills plugins mcp instalar revisar conexiones herramientas" },
  { href: "/cursos/codex-desde-cero/tareas-programadas", title: "Programa tareas que puedas revisar", section: "Codex desde cero", keywords: "scheduled tareas programadas automatizaciones resultados revisar" },
  { href: "/cursos/codex-desde-cero/cli-ide-repositorios", title: "Da el salto a CLI, IDE y repositorios cuando lo necesites", section: "Codex desde cero", keywords: "codex cli ide vscode repositorios git terminal extension" },
  { href: "/cursos/codex-desde-cero/proyecto-final", title: "Proyecto final según tu perfil", section: "Codex desde cero", keywords: "proyecto final estudiantes docentes pymes creadores desarrollo rubrica" },
  { href: "/cursos/fundamentos-aulafy", title: "Fundamentos para Aulafy", section: "Fundamentos", keywords: "python uv git terminal docker agents md ia local prerequisitos aulafy" },
  { href: "/cursos/fundamentos-aulafy/mapa-entorno", title: "Mapa del entorno local-first", section: "Fundamentos", keywords: "local first stack ia local cloud modelos privados entorno reproducible" },
  { href: "/cursos/fundamentos-aulafy/python-uv", title: "Python moderno con uv", section: "Fundamentos", keywords: "uv python venv pip entorno virtual pyproject ia local" },
  { href: "/cursos/fundamentos-aulafy/git-agents-md", title: "Git, commits pequeños y AGENTS.md", section: "Fundamentos", keywords: "git commit diff agents md instrucciones agente repositorio prompts" },
  { href: "/cursos/fundamentos-aulafy/terminal-sin-miedo", title: "Terminal sin miedo", section: "Fundamentos", keywords: "terminal cli comandos puertos procesos curl localhost" },
  { href: "/cursos/fundamentos-aulafy/docker-servicios", title: "Docker para servicios de IA", section: "Fundamentos", keywords: "docker compose qdrant n8n open webui servicios ia local" },
  { href: "/cursos/fundamentos-aulafy/proyecto-base", title: "Proyecto base listo para Aulafy", section: "Fundamentos", keywords: "plantilla proyecto ia readme gitignore pyproject verify reproducible" },
  { href: "/cursos/ai-router", title: "AI Router y sistema de contenido", section: "AI Router", keywords: "ai router litellm routing modelos locales frontier scoring shadow mode contenido" },
  { href: "/cursos/ai-router/mapa-router", title: "Mapa de un AI Router útil", section: "AI Router", keywords: "router ia modelos privacidad coste latencia fallbacks observabilidad" },
  { href: "/cursos/ai-router/litellm-gateway", title: "LiteLLM como gateway", section: "AI Router", keywords: "litellm gateway proxy virtual keys budgets rate limits fallbacks" },
  { href: "/cursos/ai-router/politicas-routing", title: "Políticas de routing", section: "AI Router", keywords: "routing policies privacidad cloud local modelo coste latencia" },
  { href: "/cursos/ai-router/quality-scoring", title: "Quality scoring sin humo", section: "AI Router", keywords: "quality scoring evals llm as judge langfuse datasets trazas" },
  { href: "/cursos/ai-router/shadow-mode", title: "Shadow mode y comparativas", section: "AI Router", keywords: "shadow mode comparativas modelos regression evals coste calidad" },
  { href: "/cursos/ai-router/proyecto-content-system", title: "Proyecto: content system para Aulafy", section: "AI Router", keywords: "content system aulafy router generación contenido revisión humana" },
  { href: "/cursos/codex-programadores", title: "Codex para programadores", section: "Codex", keywords: "openai codex curso tutorial programadores cli app agentes codigo" },
  { href: "/cursos/codex-programadores/instalacion", title: "Instala Codex y entiende sus superficies", section: "Codex", keywords: "instalar codex cli npm autenticacion app ide cloud status permissions model cursor windsurf" },
  { href: "/cursos/codex-programadores/explorar-repositorio", title: "Explora un repositorio sin perderte", section: "Codex", keywords: "codex repositorio arquitectura entender codebase rutas simbolos flujo tests monorepo multi repo workspaces" },
  { href: "/cursos/codex-programadores/pedir-cambios", title: "Pide cambios que se puedan verificar", section: "Codex", keywords: "prompt codex tarea alcance restricciones verificacion definicion terminado casos limite edge cases" },
  { href: "/cursos/codex-programadores/agents-md", title: "Enseña el repositorio con AGENTS.md", section: "Codex", keywords: "agents md instrucciones repositorio convenciones comandos jerarquia init" },
  { href: "/cursos/codex-programadores/implementar-verificar", title: "Implementa, prueba y revisa la interfaz", section: "Codex", keywords: "codex implementar tests lint build playwright ui ux verificar evidencia" },
  { href: "/cursos/codex-programadores/git-revision", title: "Trabaja con Git y revisa cambios", section: "Codex", keywords: "codex git status diff review commit branch worktree push revision codigo" },
  { href: "/cursos/codex-programadores/permisos-seguridad", title: "Controla permisos, red y secretos", section: "Codex", keywords: "codex sandbox approvals permisos red secretos prompt injection seguridad" },
  { href: "/cursos/codex-programadores/automatizar-exec", title: "Automatiza tareas con codex exec", section: "Codex", keywords: "codex exec no interactivo ci automatizacion scripts logs" },
  { href: "/cursos/codex-programadores/proyecto-final", title: "Proyecto final: entrega un cambio completo", section: "Codex", keywords: "codex proyecto final programacion tests revision entrega commit" },
  { href: "/cursos/claude-code", title: "Inicio de la guía", section: "Empezar", keywords: "home portada qué es claude code introducción" },
  { href: "/", title: "Aulafy", section: "Cursos", keywords: "aulafy portada cursos ia inteligencia artificial open source" },
  { href: "/blog", title: "Blog de IA en español", section: "Blog", keywords: "blog ia español grok modelos mcp agentes herramientas comparativas seo aeo prompts tendencias" },
  { href: "/blog/grok-45-guia-evaluacion-2026", title: "Grok 4.5: guía de evaluación sin hype", section: "Blog", keywords: "grok 4.5 xai benchmarks modelos frontier evaluar modelos ia comparativa claude chatgpt gemini" },
  { href: "/blog/crear-tutoriales-ia-x-aulafy", title: "Cómo crear tutoriales de IA para X sin humo", section: "Blog", keywords: "tutoriales ia x hilos twitter prompts contenido ia aulafy sin humo" },
  { href: "/blog/mcp-2026-07-28-migracion-guia-espanol", title: "MCP 2026-07-28 en español", section: "Blog", keywords: "mcp 2026 model context protocol migracion stateless seguridad agentes claude code n8n" },
  { href: "/blog/mejores-herramientas-ia-gratis-2026", title: "Mejores herramientas de IA gratis en 2026", section: "Blog", keywords: "mejores herramientas ia gratis 2026 inteligencia artificial gratis" },
  { href: "/blog/chatgpt-vs-claude-vs-gemini-vs-grok-2026", title: "ChatGPT vs Claude vs Gemini vs Grok en 2026", section: "Blog", keywords: "chatgpt vs claude vs gemini vs grok comparativa modelos ia" },
  { href: "/blog/como-usar-ia-para-seo-aeo-2026", title: "Cómo usar IA para SEO y AEO en 2026", section: "Blog", keywords: "ia para seo aeo geo aparecer chatgpt perplexity google ai" },
  { href: "/blog/mejores-prompts-chatgpt-claude-blogs", title: "Mejores prompts para ChatGPT y Claude si escribes blogs", section: "Blog", keywords: "prompts chatgpt blogs prompts claude español artículos seo" },
  { href: "/blog/ia-para-pymes-autonomos-casos-uso-2026", title: "IA para pymes y autónomos: 25 casos de uso", section: "Blog", keywords: "ia para pymes autonomos casos uso automatizacion empresa" },
  { href: "/blog/tendencias-ia-2026-agentes-ia-local-rag", title: "Tendencias de IA en 2026", section: "Blog", keywords: "tendencias ia 2026 agentes ia local rag automatizacion" },
  { href: "/cursos/claude-code/instalacion", title: "Instalación", section: "Empezar", keywords: "instalar npm node api key macos windows wsl linux setup actualizar" },
  { href: "/cursos/claude-code/primeros-pasos", title: "Primeros pasos", section: "Empezar", keywords: "iniciar sesión modo auto plan primera vez interfaz prompt print headless" },
  { href: "/cursos/claude-code/donde-usar", title: "CLI, app y móvil", section: "Empezar", keywords: "cli terminal app escritorio desktop web navegador vs code jetbrains ide móvil movil ios remote control dispatch teleport channels slack superficies diferencias" },
  { href: "/cursos/claude-code/recetas", title: "Recetas prácticas", section: "Práctica diaria", keywords: "ejemplos prompts copiar aprender crear errores git datos automatizar terminal documentar día a día" },
  { href: "/cursos/claude-code/proyectos", title: "Proyectos guiados", section: "Práctica diaria", keywords: "web personal app tareas to-do script python paso a paso tutorial construir proyecto" },
  { href: "/cursos/claude-code/prompts", title: "Escribir buenos prompts", section: "Práctica diaria", keywords: "prompt engineering específico contexto plantillas antes después comunicar pedir" },
  { href: "/cursos/claude-code/glosario", title: "Glosario", section: "Práctica diaria", keywords: "términos diccionario api commit backend frontend repositorio stack trace mcp deploy localhost json definiciones" },
  { href: "/cursos/claude-code/skills", title: "Skills", section: "Extender", keywords: "agent skills skill.md frontmatter reutilizable comandos personalizados automatizar invocación" },
  { href: "/cursos/claude-code/subagentes", title: "Subagentes", section: "Extender", keywords: "agentes paralelo .claude/agents revisor depurador delegar background especializado tools model" },
  { href: "/cursos/claude-code/plugins", title: "Plugins", section: "Extender", keywords: "marketplace instalar bundle plugin install anthropics extensiones paquetes" },
  { href: "/cursos/claude-code/flujos", title: "Flujos de trabajo pro", section: "Extender", keywords: "plan mode rewind checkpoint background output styles deshacer shift tab esc trucos mejores prácticas" },
  { href: "/cursos/claude-code/comandos", title: "Comandos", section: "Referencia", keywords: "slash commands flags cli atajos teclado modelos opus sonnet haiku fable help clear doctor compact" },
  { href: "/cursos/claude-code/configuracion", title: "Configuración", section: "Referencia", keywords: "settings.json claude.md memoria variables entorno modelo vscode jetbrains proxy perfiles" },
  { href: "/cursos/claude-code/mcp", title: "Servidores MCP", section: "Referencia", keywords: "model context protocol postgres github puppeteer base datos navegador api herramientas externas" },
  { href: "/cursos/claude-code/hooks", title: "Hooks", section: "Referencia", keywords: "pretoolcall posttoolcall stop automatizar prettier tests log bloquear matcher eventos" },
  { href: "/cursos/claude-code/permisos", title: "Permisos", section: "Referencia", keywords: "allow deny seguridad confirmación dangerously skip permissions herramientas control" },
  { href: "/cursos/claude-code/avanzado", title: "Uso avanzado", section: "Referencia", keywords: "subagentes worktree headless ci cd fast compact resume tmux git productividad" },
  { href: "/cursos/claude-code/faq", title: "Preguntas frecuentes", section: "Ayuda", keywords: "precio coste seguridad privacidad reemplaza programadores modelo lenguajes dudas faq" },
  { href: "/cursos/claude-code/problemas", title: "Solución de problemas", section: "Ayuda", keywords: "error command not found eacces node api key rate limit lento doctor troubleshooting arreglar" },
  { href: "/cursos/claude-code/recursos", title: "Recursos", section: "Ayuda", keywords: "enlaces links docs documentación oficial repos skills mcp cursos youtube tutoriales x twitter comunidad" },
  { href: "/cursos/claude-code/comparativa", title: "Comparativa", section: "Ayuda", keywords: "comparación versus cursor windsurf copilot chatgpt diferencias elegir herramientas" },
  { href: "/cursos/claude-code/pymes", title: "Pymes y oficina", section: "Según tu perfil", keywords: "empresa negocio autónomo oficina excel csv facturas documentos informes automatizar tareas ahorrar tiempo no programador productividad datos" },
  { href: "/cursos/claude-code/equipos", title: "Perfiles técnicos", section: "Según tu perfil", keywords: "equipos developers code review refactor testing tdd ci cd headless monorepo estandarizar plugin interno mcp integraciones avanzado" },
  { href: "/cursos/ia-local", title: "Claude Code + IA Local", section: "Volumen II", keywords: "volumen dos ia local ollama lm studio apps locales" },
  { href: "/cursos/ia-local/terminal", title: "La terminal sin miedo", section: "Volumen II", keywords: "cli terminal comandos pwd ls cd" },
  { href: "/cursos/ia-local/proyectos", title: "Cómo trabajar con tus proyectos", section: "Volumen II", keywords: "carpetas proyectos npm install dev guardar reabrir" },
  { href: "/cursos/ia-local/prompts", title: "Escribir buenos encargos", section: "Volumen II", keywords: "prompts encargos requisitos pedir aplicaciones" },
  { href: "/cursos/ia-local/ia-local", title: "IA local", section: "Volumen II", keywords: "ollama lm studio qwen gemma phi modelos locales privado evaluar comparar modelos rag json coding" },
  { href: "/cursos/ia-local/depurar", title: "Depurar y proteger", section: "Volumen II", keywords: "errores git claves seguridad backups" },
  { href: "/cursos/ia-local/chatbot-legal", title: "Chatbot legal RAG", section: "Volumen II", keywords: "rag documentos legales citar ley privacidad rgpd" },
  { href: "/cursos/ia-local/pdf", title: "Pregunta a tus PDF", section: "Volumen II", keywords: "pdf rag documentos paginas citas ocr" },
  { href: "/cursos/ia-local/voz", title: "Chatbot con voz", section: "Volumen II", keywords: "voz stt tts microfono moonshine kokoro" },
  { href: "/cursos/ia-local/texto-a-audio", title: "Texto a audio", section: "Volumen II", keywords: "tts audio mp3 kokoro magpie f5" },
  { href: "/cursos/ia-local/simulaciones-3d", title: "Simulaciones 3D", section: "Volumen II", keywords: "threejs 3d sistema solar orbitcontrols clases" },
  { href: "/cursos/ia-local/avatar", title: "Avatar que habla", section: "Volumen II", keywords: "avatar lip sync visemas cursos video" },
  { href: "/cursos/ia-local/wordpress", title: "Tema de WordPress", section: "Volumen II", keywords: "wordpress tema bloques full site editing theme json" },
  { href: "/cursos/ia-local/landing", title: "Web en minutos", section: "Volumen II", keywords: "landing web servicio publicar formulario" },
  { href: "/cursos/ia-local/facturacion", title: "Asistente para autónomos", section: "Volumen II", keywords: "facturas autonomos oficina contabilidad" },
  { href: "/cursos/ia-local/estudio", title: "App para estudiar", section: "Volumen II", keywords: "estudiar apuntes examenes preguntas flashcards" },
  { href: "/cursos/ia-local/publicar", title: "Publicar en la red", section: "Volumen II", keywords: "deploy publicar vercel internet dominio" },
  { href: "/cursos/ia-local/cluster", title: "Clúster casero", section: "Volumen II", keywords: "exo cluster ordenadores red modelos grandes" },
  { href: "/cursos/ia-generativa", title: "IA generativa: imagen, voz y vídeo", section: "IA generativa", keywords: "comfyui flux diffusers whisper piper wan imagen voz video open source" },
  { href: "/cursos/ia-generativa/mapa-licencias", title: "Mapa de herramientas y licencias", section: "IA generativa", keywords: "licencias modelos abiertos flux schnell dev apache no comercial" },
  { href: "/cursos/ia-generativa/comfyui-flux", title: "ComfyUI + FLUX desde cero", section: "IA generativa", keywords: "comfyui flux workflow imagenes generativas nodos seed" },
  { href: "/cursos/ia-generativa/diffusers-python", title: "Diffusers con Python reproducible", section: "IA generativa", keywords: "hugging face diffusers fluxpipeline python seed manifest" },
  { href: "/cursos/ia-generativa/control-lora", title: "Control, referencias y LoRA", section: "IA generativa", keywords: "lora controlnet inpainting referencias visuales consistencia sistema visual" },
  { href: "/cursos/ia-generativa/voz-local", title: "Voz local: Whisper y Piper", section: "IA generativa", keywords: "whisper piper tts stt subtitulos audio voz local" },
  { href: "/cursos/ia-generativa/video-local", title: "Vídeo local con Wan y ComfyUI", section: "IA generativa", keywords: "wan video local comfyui text to video imagen a video ffmpeg" },
  { href: "/cursos/ia-generativa/proyecto-multimodal", title: "Proyecto: cápsula educativa multimedia", section: "IA generativa", keywords: "capsula educativa multimedia manifest guion subtitulos video" },
  { href: "/cursos/seguridad-evals", title: "Seguridad y evaluación de modelos", section: "Seguridad IA", keywords: "seguridad llm evals owasp nist red teaming privacidad modelos" },
  { href: "/cursos/seguridad-evals/mapa-riesgos", title: "Mapa de riesgos de IA generativa", section: "Seguridad IA", keywords: "nist ai rmf ai act riesgos ia generativa gobernanza responsible ai sesgo fairness" },
  { href: "/cursos/seguridad-evals/owasp-llm", title: "OWASP Top 10 LLM explicado", section: "Seguridad IA", keywords: "owasp top 10 llm prompt injection output handling supply chain" },
  { href: "/cursos/seguridad-evals/evals-basicas", title: "Evals básicas y regresiones", section: "Seguridad IA", keywords: "evals llm regresiones tests modelos metricas abstencion" },
  { href: "/cursos/seguridad-evals/red-teaming", title: "Red teaming y jailbreaks", section: "Seguridad IA", keywords: "red teaming jailbreaks ailuminate adversarial prompts seguridad" },
  { href: "/cursos/seguridad-evals/privacidad-datos", title: "Privacidad, logs y datos sensibles", section: "Seguridad IA", keywords: "privacidad logs pii datos sensibles rgpd llm dataset auditing inventario datos" },
  { href: "/cursos/seguridad-evals/supply-chain", title: "Supply chain de modelos y datasets", section: "Seguridad IA", keywords: "supply chain modelos datasets hashes licencias poisoning" },
  { href: "/cursos/seguridad-evals/proyecto-auditoria", title: "Proyecto: auditoría de una app IA", section: "Seguridad IA", keywords: "auditoria ia checklist produccion riesgos evals seguridad" },
  { href: "/cursos/mlops-local", title: "MLOps local y despliegue de modelos", section: "MLOps IA", keywords: "mlops llm local vllm llama.cpp litellm langfuse despliegue modelos" },
  { href: "/cursos/mlops-local/mapa-serving", title: "Mapa de serving: Ollama, llama.cpp, vLLM", section: "MLOps IA", keywords: "serving llm ollama llama.cpp vllm ray serve openai compatible" },
  { href: "/cursos/mlops-local/llama-server", title: "llama.cpp server en local", section: "MLOps IA", keywords: "llama server gguf api local curl cuantizacion" },
  { href: "/cursos/mlops-local/vllm-openai", title: "vLLM con API compatible OpenAI", section: "MLOps IA", keywords: "vllm openai compatible gpu serving qwen api" },
  { href: "/cursos/mlops-local/litellm-gateway", title: "LiteLLM como gateway y control de costes", section: "MLOps IA", keywords: "litellm gateway proxy costes cache fallbacks rate limits" },
  { href: "/cursos/mlops-local/routing-hibrido-litellm", title: "Routing híbrido local/cloud con LiteLLM", section: "MLOps IA", keywords: "routing hibrido litellm ollama vllm cloud frontier fallback local cloud" },
  { href: "/cursos/mlops-local/migrar-cloud-local", title: "Migrar un agente cloud a local", section: "MLOps IA", keywords: "migrar agente cloud a local ollama litellm fallback evals tool calling" },
  { href: "/cursos/mlops-local/observabilidad", title: "Observabilidad con Langfuse y OpenTelemetry", section: "MLOps IA", keywords: "langfuse opentelemetry trazas logs metricas observabilidad llm model registry tracking experimentos" },
  { href: "/cursos/mlops-local/colas-costes", title: "Colas, rate limits y caché", section: "MLOps IA", keywords: "colas llm bullmq redis rate limits cache costes tokens" },
  { href: "/cursos/mlops-local/proyecto-produccion", title: "Proyecto: mini plataforma LLM privada", section: "MLOps IA", keywords: "plataforma llm privada produccion gateway observabilidad evals drift mantenimiento registry rollback" },
  { href: "/cursos/fine-tuning-local", title: "Fine-tuning y post-training de LLMs", section: "Fine-tuning", keywords: "fine tuning llm lora qlora peft trl unsloth axolotl gguf ollama" },
  { href: "/cursos/fine-tuning-local/mapa-post-training", title: "Mapa: SFT, LoRA, QLoRA y DPO", section: "Fine-tuning", keywords: "sft lora qlora dpo post training peft" },
  { href: "/cursos/fine-tuning-local/datasets-instrucciones", title: "Datasets de instrucciones de calidad", section: "Fine-tuning", keywords: "instruction dataset jsonl chat template datos sinteticos synthetic data fine tuning" },
  { href: "/cursos/fine-tuning-local/lora-qlora", title: "LoRA y QLoRA sin humo", section: "Fine-tuning", keywords: "lora qlora rank alpha learning rate overfitting" },
  { href: "/cursos/fine-tuning-local/unsloth-sft", title: "SFT rápido con Unsloth", section: "Fine-tuning", keywords: "unsloth sft lora qlora train adapter" },
  { href: "/cursos/fine-tuning-local/axolotl-config", title: "Axolotl para entrenamientos reproducibles", section: "Fine-tuning", keywords: "axolotl yaml fine tuning reproducible" },
  { href: "/cursos/fine-tuning-local/evals-overfitting", title: "Evals, overfitting y regresiones", section: "Fine-tuning", keywords: "evals fine tuning overfitting regression test llm dpo orpo preference tuning" },
  { href: "/cursos/fine-tuning-local/export-gguf-ollama", title: "Exportar a GGUF y Ollama", section: "Fine-tuning", keywords: "export lora gguf ollama modelfile quantizacion" },
  { href: "/cursos/fine-tuning-local/proyecto-modelo-pyme", title: "Proyecto: modelo adaptado para una pyme", section: "Fine-tuning", keywords: "modelo adaptado pyme soporte lora fine tuning local" },
  { href: "/cursos/agentes-automatizacion", title: "Agentes y automatización", section: "Agentes IA", keywords: "agentes ia automatizacion claude code skills subagentes hooks mcp loops routines" },
  { href: "/cursos/agentes-automatizacion/mapa", title: "Mapa real de agentes en 2026", section: "Agentes IA", keywords: "taxonomia agentes skills subagentes hooks mcp loop routines github actions langgraph crewai n8n" },
  { href: "/cursos/agentes-automatizacion/subagentes", title: "Subagentes con roles y límites", section: "Agentes IA", keywords: "subagentes roles reviewer investigator implementador contexto aislado" },
  { href: "/crear-cli-agentes-ia-local", title: "Crear una CLI de agentes IA local", section: "Agentes IA", keywords: "crear cli agentes ia local python r cli aulafy ollama click rich sqlite workflows permisos tutorial" },
  { href: "/cursos/agentes-automatizacion/crear-cli-tipo-r", title: "Crear una CLI de agentes tipo R", section: "Agentes IA", keywords: "r cli aulafy crear cli agentes ia local python click rich ollama skills permisos workflows sqlite" },
  { href: "/cursos/agentes-automatizacion/hooks", title: "Hooks: automatización determinista", section: "Agentes IA", keywords: "hooks pretooluse posttooluse bloquear comandos tests seguridad" },
  { href: "/cursos/agentes-automatizacion/skills-seguras", title: "Skills seguras y auditables", section: "Agentes IA", keywords: "skills seguras skill.md allowed-tools auditoria bash secretos" },
  { href: "/cursos/agentes-automatizacion/mcp-seguro", title: "MCP sin regalar tus llaves", section: "Agentes IA", keywords: "mcp seguro oauth tokens allowlist servidores herramientas externas" },
  { href: "/cursos/agentes-automatizacion/mcp-herramientas-locales", title: "MCP para herramientas locales", section: "Agentes IA", keywords: "mcp herramientas locales tools filesystem comandos allowlist trazas permisos" },
  { href: "/cursos/agentes-automatizacion/servidor-mcp-custom", title: "Crear un servidor MCP personalizado", section: "Agentes IA", keywords: "crear servidor mcp custom python fastmcp tools debug codigo" },
  { href: "/cursos/agentes-automatizacion/github-routines", title: "GitHub Actions y routines", section: "Agentes IA", keywords: "github actions routines loop cron pr review agentes programados" },
  { href: "/cursos/agentes-automatizacion/agente-247", title: "Proyecto: agente 24/7 con bandeja de entrada", section: "Agentes IA", keywords: "agente 24/7 telegram discord vps mini pc cola aprobacion humana" },
  { href: "/cursos/agentes-automatizacion/agentes-247-hardware-real", title: "Agentes 24/7 offline en hardware real", section: "Agentes IA", keywords: "agente autonomo local 24/7 mac m4 rtx 3090 low vram watchdog offline" },
  { href: "/cursos/agentes-automatizacion/oom-memory", title: "OOM y gestión de memoria", section: "Agentes IA", keywords: "oom out of memory agentes langgraph n8n truncation summarization queue mode" },
  { href: "/cursos/agentes-automatizacion/retry-idempotencia", title: "Retries, idempotencia y exactly-once", section: "Agentes IA", keywords: "retry logic idempotencia exactly once tool calling duplicado agentes" },
  { href: "/cursos/agentes-automatizacion/estado-recuperacion", title: "Estado persistente y crash recovery", section: "Agentes IA", keywords: "persistent state crash recovery langgraph checkpointer temporal durable execution active tasks" },
  { href: "/cursos/agentes-automatizacion/loops-costes", title: "Loops infinitos y control de costes", section: "Agentes IA", keywords: "loops infinitos costes circuit breaker budget guardrails agentes ia" },
  { href: "/cursos/agentes-automatizacion/multiagentes-locales-loops", title: "Multi-agentes locales, memoria y loops", section: "Agentes IA", keywords: "multi agente local subagentes persistencia runaway agent loop ollama hermes compute budget" },
  { href: "/cursos/agentes-automatizacion/memoria-persistente-compartida", title: "Memoria persistente compartida", section: "Agentes IA", keywords: "memoria persistente compartida agentes qdrant obsidian hot warm cold" },
  { href: "/cursos/agentes-automatizacion/mcp-governance", title: "Governance MCP y conocimiento fiable", section: "Agentes IA", keywords: "mcp governance conocimiento fiable permisos scopes fuentes aprobaciones" },
  { href: "/cursos/agentes-produccion/observabilidad-agentes-locales", title: "Observabilidad para agentes locales", section: "Agentes en producción", keywords: "observabilidad agentes locales langfuse opentelemetry traces tools rag" },
  { href: "/cursos/rag-seguro/obsidian-segundo-cerebro", title: "Segundo cerebro local con Obsidian y RAG", section: "RAG seguro", keywords: "obsidian segundo cerebro rag markdown qdrant notas locales" },
  { href: "/cursos/rag-seguro/evals-metricas", title: "Evals RAG con métricas", section: "RAG seguro", keywords: "evals rag metricas faithfulness recall abstencion permisos dataset auditing multimodal ocr" },
  { href: "/cursos/rag-seguro/evals-citaciones", title: "Evals, citaciones y trazabilidad", section: "RAG seguro", keywords: "evals citaciones trazabilidad fuentes grounding multimodal ocr tablas" },
  { href: "/cursos/automatizacion-self-hosted", title: "Automatización IA self-hosted para pymes", section: "Automatización self-hosted", keywords: "n8n open webui ollama self hosted pymes vps docker automatizacion ia" },
  { href: "/cursos/automatizacion-self-hosted/mapa-stack", title: "Mapa del stack: n8n, Open WebUI y modelos", section: "Automatización self-hosted", keywords: "stack n8n open webui ollama vllm modelos locales pymes" },
  { href: "/cursos/automatizacion-self-hosted/docker-vps", title: "Docker y VPS barato sin liarla", section: "Automatización self-hosted", keywords: "docker vps barato self hosted ia n8n open webui backups" },
  { href: "/cursos/automatizacion-self-hosted/stack-docker-ia-local", title: "Docker Compose para stack completo de IA local", section: "Automatización self-hosted", keywords: "docker compose ia local ollama open webui qdrant n8n profiles stack" },
  { href: "/cursos/automatizacion-self-hosted/ollama-openwebui", title: "Ollama y Open WebUI como interfaz privada", section: "Automatización self-hosted", keywords: "ollama open webui interfaz privada tools funciones modelos locales" },
  { href: "/cursos/automatizacion-self-hosted/rag-n8n-qdrant-ollama", title: "RAG privado con n8n, Qdrant y Ollama", section: "Automatización self-hosted", keywords: "rag privado n8n qdrant ollama telegram open webui faq agent workflow" },
  { href: "/cursos/automatizacion-self-hosted/n8n-webhooks", title: "n8n con webhooks y credenciales", section: "Automatización self-hosted", keywords: "n8n webhooks credenciales workflows ia agentes pymes" },
  { href: "/cursos/automatizacion-self-hosted/aprobaciones-humanas", title: "Aprobaciones humanas antes de actuar", section: "Automatización self-hosted", keywords: "human in the loop aprobaciones n8n telegram email seguridad" },
  { href: "/cursos/automatizacion-self-hosted/colas-backups-monitoring", title: "Colas, backups y monitorización", section: "Automatización self-hosted", keywords: "n8n queue mode redis workers backups monitoring error workflow" },
  { href: "/cursos/automatizacion-self-hosted/proyecto-soporte-pyme", title: "Proyecto: soporte interno para una pyme", section: "Automatización self-hosted", keywords: "proyecto soporte pyme n8n open webui ollama borradores aprobacion" },
  { href: "/cursos/ia-local/hermes-agente-coding-local", title: "Agente coding local con Hermes y Ollama", section: "IA local", keywords: "hermes agent ollama gemma qwen coding agent local tool calling stop logic memoria" },
  { href: "/cursos/ia-local/hermes-gemma-mlx-avanzado", title: "Hermes avanzado con Gemma y MLX", section: "IA local", keywords: "hermes agent gemma mlx apple silicon mixture of agents skills local" },
  { href: "/cursos/ia-local/tool-calling-modelos-locales", title: "Tool calling con modelos locales", section: "IA local", keywords: "tool calling modelos locales ollama hermes mcp open webui function calling parser" },
  { href: "/cursos/ia-local/webapp-tipo-lexia", title: "Web app tipo Lexia con RAG local", section: "IA local", keywords: "lexia web app rag local lm studio embeddings citas guardrails vercel node" },
  { href: "/cursos/ia-local/ollama-vllm-sglang-mlx", title: "Ollama, vLLM, SGLang y MLX: qué usar", section: "IA local", keywords: "ollama vs vllm sglang mlx apple silicon serving llm local runtime inferencia modelos locales" },
  { href: "/cursos/ia-pymes/mapa", title: "Mapa de IA útil para una pyme", section: "IA para pymes", keywords: "ia pyme casos uso oficina emails facturas presupuestos humano roi valor automatizacion" },
  { href: "/cursos/rag-seguro/chunking-avanzado", title: "Chunking avanzado para RAG privado", section: "RAG seguro", keywords: "chunking avanzado rag semantic overlap metadata headings qdrant" },
  { href: "/cursos/rag-seguro/graphrag-local", title: "GraphRAG local y memoria con grafos", section: "RAG seguro", keywords: "graphrag local rag grafos knowledge graph memoria agentes relaciones entidades" },
  { href: "/cursos/rag-seguro/respuestas-estructuradas-citas", title: "Respuestas estructuradas con citas", section: "RAG seguro", keywords: "rag respuestas estructuradas citas confidence no se json citations" },
  { href: "/cursos/ia-pymes/facturas-verifactu-ocr", title: "Facturas, OCR y Verifactu con revisión humana", section: "IA para pymes", keywords: "verifactu ia ocr facturas factura electronica autonomos pymes españa revision humana" },
  { href: "/cursos/ia-pymes/aeo-pymes", title: "AEO para pymes: aparecer en respuestas de IA", section: "IA para pymes", keywords: "aeo pymes aparecer chatgpt perplexity grok seo agentes respuestas ia negocio local" },
  { href: "/cursos/videojuegos-3d-ia", title: "Videojuegos, 3D y simulaciones con IA", section: "Videojuegos 3D IA", keywords: "videojuegos 3d ia fable 5 godot blender unity autocad cad simulaciones" },
  { href: "/cursos/videojuegos-3d-ia/introduccion", title: "Fable 5 para videojuegos, 3D y simulaciones", section: "Videojuegos 3D IA", keywords: "fable 5 videojuegos claude fable 5 game dev 3d simulaciones" },
  { href: "/cursos/videojuegos-3d-ia/setup-blender-godot", title: "Setup Blender, Godot y Fable 5", section: "Videojuegos 3D IA", keywords: "setup blender godot fable 5 mcp glb gltf proyecto 3d" },
  { href: "/cursos/videojuegos-3d-ia/assets-3d-ia", title: "Assets 3D con IA: limpiar y exportar", section: "Videojuegos 3D IA", keywords: "assets 3d ia glb gltf blender unity godot pbr texturas pipeline rendimiento presupuesto" },
  { href: "/cursos/videojuegos-3d-ia/npc-llm-local-godot", title: "NPC con LLM local y memoria en Godot", section: "Videojuegos 3D IA", keywords: "npc llm local godot ollama dialogos dinamicos memoria videojuegos ia" },
  { href: "/cursos/videojuegos-3d-ia/prototipo-godot", title: "Primer prototipo 3D en Godot", section: "Videojuegos 3D IA", keywords: "godot 4 prototipo 3d characterbody3d gdscript juego ia" },
  { href: "/cursos/videojuegos-3d-ia/cad-validacion", title: "IA, CAD y validación profesional", section: "Videojuegos 3D IA", keywords: "ia cad autocad fusion revit bim autolisp validacion tolerancias interferencias" },
  { href: "/aviso-legal", title: "Aviso legal", section: "Legal", keywords: "aviso legal titular responsable contacto lssi condiciones uso" },
  { href: "/licencia", title: "Licencia", section: "Legal", keywords: "cc by mit contenido codigo reutilizar" },
  { href: "/privacidad", title: "Privacidad", section: "Legal", keywords: "privacidad cookies chat groq datos ip" },
  { href: "/cookies", title: "Cookies", section: "Legal", keywords: "cookies localstorage modo claro oscuro sin analitica publicidad seguimiento" },
];
