export type CourseLocale = "es" | "en";

type Bilingual = { es: string; en: string };
type SourceKey = "openai" | "anthropic" | "nist" | "owasp" | "unesco" | "hf" | "ollama" | "mcp" | "langgraph" | "n8n" | "vercel" | "eu";

export type UnifiedLesson = {
  id: string;
  title: Bilingual;
  summary: Bilingual;
  outcomes: Bilingual[];
  explanation: Bilingual[];
  practice: Bilingual;
  evidence: Bilingual;
  sources: SourceKey[];
  volatility: "stable" | "reviewable" | "volatile";
};

export type UnifiedModule = {
  id: string;
  title: Bilingual;
  purpose: Bilingual;
  lessons: UnifiedLesson[];
};

export type ModuleProject = {
  title: Bilingual;
  scenario: Bilingual;
  deliverables: Bilingual[];
  checks: Bilingual[];
};

export const unifiedSources: Record<SourceKey, { label: string; href: string }> = {
  openai: { label: "OpenAI · Documentation", href: "https://platform.openai.com/docs" },
  anthropic: { label: "Anthropic · Documentation", href: "https://docs.anthropic.com/" },
  nist: { label: "NIST · AI Risk Management Framework", href: "https://www.nist.gov/itl/ai-risk-management-framework" },
  owasp: { label: "OWASP · Top 10 for LLM Applications", href: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" },
  unesco: { label: "UNESCO · Guidance for generative AI in education", href: "https://www.unesco.org/en/articles/guidance-generative-ai-education-and-research" },
  hf: { label: "Hugging Face · Model Cards", href: "https://huggingface.co/docs/hub/en/model-cards" },
  ollama: { label: "Ollama · Documentation", href: "https://docs.ollama.com/" },
  mcp: { label: "Model Context Protocol · Documentation", href: "https://modelcontextprotocol.io/" },
  langgraph: { label: "LangGraph · Documentation", href: "https://docs.langchain.com/oss/python/langgraph/overview" },
  n8n: { label: "n8n · Documentation", href: "https://docs.n8n.io/" },
  vercel: { label: "Vercel · Documentation", href: "https://vercel.com/docs" },
  eu: { label: "European Commission · AI regulatory framework", href: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai" },
};

const b = (es: string, en: string): Bilingual => ({ es, en });
const lesson = (value: UnifiedLesson) => value;

export const unifiedModules: UnifiedModule[] = [
  {
    id: "fundamentos",
    title: b("1. Entender la IA", "1. Understand AI"),
    purpose: b("Construye un modelo mental correcto antes de elegir herramientas.", "Build a sound mental model before choosing tools."),
    lessons: [
      lesson({ id: "que-es-ia-generativa", title: b("Qué es la IA generativa", "What generative AI is"), summary: b("Un modelo predice una salida probable; no consulta una verdad universal.", "A model predicts a likely output; it does not query universal truth."), outcomes: [b("Distinguir modelo, interfaz y herramienta", "Separate model, interface, and tool"), b("Reconocer tareas apropiadas y límites", "Recognize suitable tasks and limits")], explanation: [b("Los modelos generan texto, imágenes, audio o código a partir de patrones aprendidos. Una respuesta convincente puede ser incorrecta.", "Models generate text, images, audio, or code from learned patterns. A convincing answer can still be wrong."), b("Úsalos para proponer, transformar, resumir o explorar. Conserva la decisión humana cuando el error pueda afectar a personas, dinero, derechos o seguridad.", "Use them to propose, transform, summarize, or explore. Keep human decisions where errors can affect people, money, rights, or safety.")], practice: b("Elige una tarea cotidiana y sepárala en: borrador delegable, comprobación humana y decisión final.", "Choose an everyday task and split it into: delegable draft, human check, and final decision."), evidence: b("Una tabla de tres columnas con los límites de delegación.", "A three-column table describing delegation limits."), sources: ["nist", "unesco"], volatility: "stable" }),
      lesson({ id: "familias-de-sistemas", title: b("Chat, búsqueda, RAG, automatización y agentes", "Chat, search, RAG, automation, and agents"), summary: b("No todos los problemas necesitan un agente.", "Not every problem needs an agent."), outcomes: [b("Elegir la arquitectura mínima", "Choose the smallest architecture"), b("Evitar autonomía innecesaria", "Avoid unnecessary autonomy")], explanation: [b("Un chat responde; la búsqueda localiza; RAG aporta documentos; una automatización sigue pasos definidos; un agente decide qué herramienta usar.", "Chat answers; search locates; RAG supplies documents; automation follows defined steps; an agent chooses which tool to use."), b("Empieza por el mecanismo menos autónomo que resuelva el problema. Añade memoria, herramientas o bucles solo si puedes probar su necesidad.", "Start with the least autonomous mechanism that solves the problem. Add memory, tools, or loops only when you can prove the need.")], practice: b("Clasifica cinco tareas reales y justifica la opción más simple para cada una.", "Classify five real tasks and justify the simplest option for each."), evidence: b("Una decisión por tarea y un riesgo que evitarías.", "One decision per task and one risk you would avoid."), sources: ["nist", "owasp"], volatility: "reviewable" }),
      lesson({ id: "verificar-respuestas", title: b("Alucinaciones y verificación", "Hallucinations and verification"), summary: b("La fluidez no es evidencia.", "Fluency is not evidence."), outcomes: [b("Detectar afirmaciones comprobables", "Spot verifiable claims"), b("Contrastar con fuentes primarias", "Check primary sources")], explanation: [b("Separa hechos, inferencias y recomendaciones. Para cada hecho importante pide una fuente y comprueba que realmente respalda la afirmación.", "Separate facts, inferences, and recommendations. For each important fact, request a source and verify that it truly supports the claim."), b("Si no hay evidencia suficiente, la respuesta correcta es abstenerse o declarar incertidumbre.", "When evidence is insufficient, the correct behavior is to abstain or state uncertainty.")], practice: b("Audita una respuesta con tres afirmaciones y marca: confirmada, contradictoria o sin evidencia.", "Audit an answer with three claims and mark each as confirmed, contradicted, or unsupported."), evidence: b("Enlaces, fragmento comprobado y conclusión propia.", "Links, checked excerpt, and your own conclusion."), sources: ["nist", "unesco"], volatility: "stable" }),
    ],
  },
  {
    id: "trabajo",
    title: b("2. Trabajar y estudiar con IA", "2. Work and study with AI"),
    purpose: b("Obtén resultados útiles sin ceder criterio, privacidad ni aprendizaje.", "Get useful results without giving up judgment, privacy, or learning."),
    lessons: [
      lesson({ id: "encargos-claros", title: b("Encargos claros, no prompts mágicos", "Clear briefs, not magic prompts"), summary: b("Objetivo, contexto, restricciones y criterio de aceptación.", "Goal, context, constraints, and acceptance criteria."), outcomes: [b("Redactar encargos verificables", "Write verifiable briefs"), b("Iterar con evidencia", "Iterate with evidence")], explanation: [b("Un buen encargo describe el resultado observable, los datos permitidos, lo que no debe ocurrir y cómo se comprobará.", "A good brief describes the observable result, allowed data, forbidden behavior, and how it will be checked."), b("Pide primero un plan o muestra pequeña cuando el trabajo sea costoso o difícil de deshacer.", "Ask for a plan or small sample first when the work is costly or hard to reverse.")], practice: b("Convierte una petición vaga en un encargo con cinco criterios de aceptación.", "Turn a vague request into a brief with five acceptance criteria."), evidence: b("Petición original, versión mejorada y lista de comprobación.", "Original request, improved version, and checklist."), sources: ["openai", "anthropic"], volatility: "reviewable" }),
      lesson({ id: "estudiar-sin-delegar", title: b("Estudiar sin delegar el aprendizaje", "Study without outsourcing learning"), summary: b("La IA puede explicar y preguntar; tú debes recuperar y aplicar.", "AI can explain and quiz; you must retrieve and apply."), outcomes: [b("Usar recuperación activa", "Use active recall"), b("Evitar entregar trabajo no comprendido", "Avoid submitting work you do not understand")], explanation: [b("Pide explicaciones graduadas, ejemplos y preguntas. Después cierra el chat y reconstruye la idea con tus palabras.", "Request graded explanations, examples, and questions. Then close the chat and reconstruct the idea in your own words."), b("Declara el uso de IA cuando la institución lo exija y nunca inventes fuentes, datos o experimentos.", "Disclose AI use when your institution requires it, and never fabricate sources, data, or experiments.")], practice: b("Estudia un concepto durante diez minutos y explícalo sin mirar la respuesta.", "Study one concept for ten minutes and explain it without looking at the answer."), evidence: b("Primera explicación, errores detectados y segunda explicación.", "First explanation, detected errors, and second explanation."), sources: ["unesco", "nist"], volatility: "stable" }),
      lesson({ id: "privacidad-datos", title: b("Privacidad y datos sensibles", "Privacy and sensitive data"), summary: b("Minimiza antes de copiar.", "Minimize before you paste."), outcomes: [b("Clasificar información antes de enviarla", "Classify information before sending it"), b("Anonimizar y reducir contexto", "Anonymize and reduce context")], explanation: [b("No introduzcas secretos, historiales médicos, expedientes, credenciales o datos de terceros sin base, autorización y controles adecuados.", "Do not enter secrets, medical records, case files, credentials, or third-party data without a lawful basis, authorization, and proper controls."), b("Sustituye datos reales por ejemplos ficticios y comparte solo el fragmento necesario para la tarea.", "Replace real data with fictional examples and share only the fragment needed for the task." )], practice: b("Limpia un documento ficticio antes de usarlo en un modelo.", "Sanitize a fictional document before using it with a model."), evidence: b("Lista de datos eliminados, sustituidos y conservados.", "List of removed, replaced, and retained data."), sources: ["nist", "eu"], volatility: "reviewable" }),
    ],
  },
  {
    id: "datos-rag",
    title: b("3. Datos, búsqueda y RAG", "3. Data, search, and RAG"),
    purpose: b("Construye respuestas trazables sobre documentos y datos reales.", "Build traceable answers over real documents and data."),
    lessons: [
      lesson({ id: "preparar-datos", title: b("Preparar datos antes del modelo", "Prepare data before the model"), summary: b("Tipos, calidad y procedencia primero.", "Types, quality, and provenance first."), outcomes: [b("Perfilar datos", "Profile data"), b("Conservar procedencia", "Preserve provenance")], explanation: [b("Comprueba columnas, tipos, unidades, nulos, duplicados y fechas antes de pedir conclusiones. La IA no corrige silenciosamente una base defectuosa.", "Check columns, types, units, nulls, duplicates, and dates before asking for conclusions. AI does not silently repair a broken dataset."), b("Cada transformación debe poder reconstruirse y revisarse.", "Every transformation must be reproducible and reviewable.")], practice: b("Perfila un CSV pequeño y escribe cinco controles de calidad.", "Profile a small CSV and write five quality checks."), evidence: b("Informe de perfil, anomalías y decisiones de limpieza.", "Profile report, anomalies, and cleaning decisions."), sources: ["nist"], volatility: "stable" }),
      lesson({ id: "rag-minimo", title: b("RAG mínimo con citas", "Minimal RAG with citations"), summary: b("Recuperar evidencia antes de responder.", "Retrieve evidence before answering."), outcomes: [b("Entender ingesta, fragmentos y recuperación", "Understand ingestion, chunks, and retrieval"), b("Exigir citas útiles", "Require useful citations")], explanation: [b("RAG divide documentos, crea representaciones para buscar y entrega fragmentos relevantes al modelo. No convierte documentos erróneos en verdad.", "RAG splits documents, builds representations for retrieval, and supplies relevant passages to the model. It does not turn incorrect documents into truth."), b("Una cita debe permitir localizar el documento y el pasaje que sostiene la respuesta.", "A citation should locate the document and passage supporting the answer.")], practice: b("Diseña un conjunto de diez preguntas: ocho respondibles y dos fuera de alcance.", "Design ten questions: eight answerable and two out of scope."), evidence: b("Preguntas, pasajes recuperados, respuestas y abstenciones.", "Questions, retrieved passages, answers, and abstentions."), sources: ["owasp", "nist"], volatility: "reviewable" }),
      lesson({ id: "evaluar-rag", title: b("Evaluar recuperación y respuesta", "Evaluate retrieval and answers"), summary: b("Mide búsqueda y generación por separado.", "Measure retrieval and generation separately."), outcomes: [b("Crear un conjunto de evaluación", "Create an evaluation set"), b("Distinguir fallo de búsqueda y fallo de respuesta", "Separate retrieval failure from answer failure")], explanation: [b("Registra si el pasaje correcto apareció, si la respuesta se apoyó en él, si citó bien y si se abstuvo cuando debía.", "Record whether the correct passage appeared, whether the answer used it, whether citations were correct, and whether it abstained when required."), b("No mejores el prompt para ocultar un buscador que recupera documentos equivocados.", "Do not improve the prompt to hide a retriever that returns the wrong documents.")], practice: b("Evalúa manualmente veinte casos y agrupa los fallos por causa.", "Manually evaluate twenty cases and group failures by cause."), evidence: b("Tabla de métricas, ejemplos fallidos y próxima hipótesis.", "Metrics table, failed examples, and next hypothesis."), sources: ["nist", "owasp"], volatility: "reviewable" }),
    ],
  },
  {
    id: "construir",
    title: b("4. Construir software con IA", "4. Build software with AI"),
    purpose: b("Pasa de una idea a software mantenible sin entregar el control del repositorio.", "Move from an idea to maintainable software without surrendering repository control."),
    lessons: [
      lesson({ id: "especificar", title: b("Especificar antes de generar", "Specify before generating"), summary: b("Problema, usuario, datos, estados y aceptación.", "Problem, user, data, states, and acceptance."), outcomes: [b("Crear una especificación pequeña", "Create a small specification"), b("Reducir retrabajo", "Reduce rework")], explanation: [b("Define quién usa el producto, qué problema resuelve, qué datos toca y qué estados debe mostrar. Incluye carga, vacío, error y éxito.", "Define who uses the product, which problem it solves, which data it touches, and which states it must show. Include loading, empty, error, and success."), b("Construye primero un recorrido completo pequeño; amplía después de probarlo.", "Build one small end-to-end path first; expand after testing it." )], practice: b("Escribe una especificación de una página para una herramienta útil.", "Write a one-page specification for a useful tool."), evidence: b("Flujo principal, cinco criterios y tres riesgos.", "Main flow, five criteria, and three risks."), sources: ["openai", "anthropic"], volatility: "reviewable" }),
      lesson({ id: "agentes-codigo", title: b("Agentes de código con límites", "Coding agents with boundaries"), summary: b("Explorar, planificar, cambiar, probar y revisar.", "Explore, plan, change, test, and review."), outcomes: [b("Dar contexto sin sobreexponer", "Provide context without overexposure"), b("Revisar diffs y pruebas", "Review diffs and tests")], explanation: [b("Empieza en solo lectura. Pide al agente que identifique archivos, restricciones y pruebas antes de editar.", "Start read-only. Ask the agent to identify files, constraints, and tests before editing."), b("Revisa el diff, ejecuta comprobaciones proporcionales al riesgo y conserva una forma de volver atrás.", "Review the diff, run checks proportional to risk, and keep a rollback path." )], practice: b("Encarga un cambio pequeño en una rama y revisa cada archivo modificado.", "Delegate a small change on a branch and review every modified file."), evidence: b("Plan, diff, salida de pruebas y decisión de aceptar o corregir.", "Plan, diff, test output, and accept-or-fix decision."), sources: ["openai", "anthropic"], volatility: "volatile" }),
      lesson({ id: "publicar-web", title: b("Publicar una web seria", "Publish a production-minded website"), summary: b("Accesibilidad, seguridad, SEO y operación mínima.", "Accessibility, security, SEO, and minimum operations."), outcomes: [b("Preparar preview y producción", "Prepare preview and production"), b("Comprobar móvil, teclado y errores", "Check mobile, keyboard, and errors")], explanation: [b("Una web no termina cuando compila. Comprueba navegación, contraste, formularios, metadatos, secretos, dominio y recuperación ante un despliegue defectuoso.", "A website is not finished when it compiles. Check navigation, contrast, forms, metadata, secrets, domain, and recovery from a bad deployment."), b("Mantén preview y producción separados y documenta variables externas y costes.", "Keep preview and production separate, and document external variables and costs." )], practice: b("Publica una página mínima en preview, pruébala y documenta el rollback.", "Publish a minimal page to preview, test it, and document rollback."), evidence: b("URL de preview, checklist y procedimiento de vuelta atrás.", "Preview URL, checklist, and rollback procedure."), sources: ["vercel", "owasp"], volatility: "volatile" }),
    ],
  },
  {
    id: "local",
    title: b("5. IA local y modelos abiertos", "5. Local AI and open models"),
    purpose: b("Elige hardware, modelos y licencias con expectativas realistas.", "Choose hardware, models, and licenses with realistic expectations."),
    lessons: [
      lesson({ id: "elegir-modelo", title: b("Elegir un modelo con evidencia", "Choose a model with evidence"), summary: b("Tarea, licencia, memoria, calidad y coste.", "Task, license, memory, quality, and cost."), outcomes: [b("Leer una model card", "Read a model card"), b("Evitar rankings universales", "Avoid universal rankings")], explanation: [b("Compara modelos con tus propios casos. Revisa licencia, idiomas, contexto, requisitos de memoria y límites publicados.", "Compare models on your own cases. Review license, languages, context, memory requirements, and published limits."), b("Open weights no significa necesariamente open source ni permiso ilimitado para cualquier uso.", "Open weights does not necessarily mean open source or unlimited permission for every use." )], practice: b("Compara dos modelos con diez ejemplos de tu tarea y la misma rúbrica.", "Compare two models on ten examples from your task using the same rubric."), evidence: b("Model cards, hardware, resultados y decisión justificada.", "Model cards, hardware, results, and justified decision."), sources: ["hf", "nist"], volatility: "volatile" }),
      lesson({ id: "ollama-local", title: b("Primer servicio local con Ollama", "First local service with Ollama"), summary: b("Descarga, ejecuta, mide y limita exposición.", "Download, run, measure, and limit exposure."), outcomes: [b("Ejecutar un modelo local", "Run a local model"), b("Medir memoria y latencia", "Measure memory and latency")], explanation: [b("Ollama simplifica la ejecución local, pero el modelo sigue consumiendo almacenamiento, RAM o VRAM. No expongas el servicio a Internet sin autenticación y controles.", "Ollama simplifies local execution, but the model still consumes storage, RAM, or VRAM. Do not expose the service to the Internet without authentication and controls."), b("Registra versión, modelo exacto, cuantización y hardware para que la prueba sea reproducible.", "Record version, exact model, quantization, and hardware so the test is reproducible." )], practice: b("Ejecuta un modelo pequeño y mide tiempo hasta la primera respuesta y memoria usada.", "Run a small model and measure time to first response and memory use."), evidence: b("Comando, versiones, hardware y mediciones.", "Command, versions, hardware, and measurements."), sources: ["ollama", "hf"], volatility: "volatile" }),
      lesson({ id: "local-vs-api", title: b("Local, API o híbrido", "Local, API, or hybrid"), summary: b("No conviertas una preferencia en una ideología.", "Do not turn a preference into an ideology."), outcomes: [b("Comparar privacidad, calidad y operación", "Compare privacy, quality, and operations"), b("Diseñar fallback", "Design fallback")], explanation: [b("Local puede reducir salida de datos y coste variable, pero añade hardware y mantenimiento. Una API puede ofrecer mayor capacidad, pero introduce dependencia, tratamiento externo y coste por uso.", "Local can reduce data egress and variable cost, but adds hardware and maintenance. An API can offer greater capability, but introduces dependency, external processing, and usage cost."), b("Un diseño híbrido decide por política qué tareas y datos pueden usar cada ruta.", "A hybrid design uses policy to decide which tasks and data may use each route." )], practice: b("Crea una matriz de decisión para tres tareas reales.", "Create a decision matrix for three real tasks."), evidence: b("Criterios, pesos, decisión y condición de cambio.", "Criteria, weights, decision, and change condition."), sources: ["nist", "ollama", "openai"], volatility: "reviewable" }),
    ],
  },
  {
    id: "agentes",
    title: b("6. Automatización y agentes", "6. Automation and agents"),
    purpose: b("Automatiza de forma observable, reversible y con permisos mínimos.", "Automate with observability, reversibility, and least privilege."),
    lessons: [
      lesson({ id: "automatizar-flujo", title: b("Del procedimiento al flujo", "From procedure to workflow"), summary: b("Estabiliza el proceso antes de automatizarlo.", "Stabilize the process before automating it."), outcomes: [b("Representar pasos y excepciones", "Map steps and exceptions"), b("Definir revisión humana", "Define human review")], explanation: [b("Documenta entradas, decisiones, salidas, responsables y fallos. Si las personas no acuerdan el proceso, un agente solo automatizará la confusión.", "Document inputs, decisions, outputs, owners, and failures. If people do not agree on the process, an agent will only automate confusion."), b("Separa propuesta, aprobación y ejecución cuando la acción pueda causar daño.", "Separate proposal, approval, and execution when an action can cause harm." )], practice: b("Dibuja un flujo de oficina y marca cada punto de aprobación.", "Diagram an office workflow and mark every approval point."), evidence: b("Diagrama, responsable, datos y modo manual alternativo.", "Diagram, owner, data, and manual fallback."), sources: ["n8n", "nist"], volatility: "reviewable" }),
      lesson({ id: "herramientas-mcp", title: b("Herramientas y MCP", "Tools and MCP"), summary: b("Una herramienta amplía también el riesgo.", "A tool expands risk as well as capability."), outcomes: [b("Entender cliente, servidor y permiso", "Understand client, server, and permission"), b("Aplicar mínimo privilegio", "Apply least privilege")], explanation: [b("MCP estandariza cómo una aplicación ofrece recursos y herramientas a un modelo. No convierte una herramienta insegura en segura.", "MCP standardizes how an application exposes resources and tools to a model. It does not make an unsafe tool safe."), b("Limita alcance, valida argumentos, registra llamadas y exige aprobación para escritura, pagos, publicación o borrado.", "Limit scope, validate arguments, log calls, and require approval for writes, payments, publishing, or deletion." )], practice: b("Diseña el contrato de una herramienta de solo lectura y sus controles.", "Design the contract and controls for a read-only tool."), evidence: b("Esquema de entrada, salida, errores y permisos.", "Input, output, errors, and permissions schema."), sources: ["mcp", "owasp"], volatility: "volatile" }),
      lesson({ id: "estado-reintentos", title: b("Estado, reintentos e idempotencia", "State, retries, and idempotency"), summary: b("Un fallo no debe duplicar una acción.", "A failure must not duplicate an action."), outcomes: [b("Guardar estado recuperable", "Store recoverable state"), b("Diseñar operaciones idempotentes", "Design idempotent operations")], explanation: [b("Los agentes fallan por red, límites, procesos o respuestas inválidas. Guarda cada transición y distingue intento, aprobación y ejecución.", "Agents fail because of networks, limits, processes, or invalid responses. Store each transition and separate attempt, approval, and execution."), b("Usa claves de idempotencia, límites de reintento y una cola de revisión para casos ambiguos.", "Use idempotency keys, retry limits, and a review queue for ambiguous cases." )], practice: b("Simula un fallo después de ejecutar y antes de confirmar.", "Simulate a failure after execution but before confirmation."), evidence: b("Traza que demuestra que la acción no se duplicó.", "Trace proving that the action was not duplicated."), sources: ["langgraph", "n8n"], volatility: "volatile" }),
    ],
  },
  {
    id: "produccion",
    title: b("7. Producción, seguridad y proyecto final", "7. Production, safety, and capstone"),
    purpose: b("Opera sistemas útiles y demuestra lo aprendido con evidencia.", "Operate useful systems and prove learning with evidence."),
    lessons: [
      lesson({ id: "evals-observabilidad", title: b("Evals, logs y observabilidad", "Evals, logs, and observability"), summary: b("No puedes mejorar lo que no puedes reconstruir.", "You cannot improve what you cannot reconstruct."), outcomes: [b("Definir casos de evaluación", "Define evaluation cases"), b("Registrar trazas útiles sin filtrar datos", "Log useful traces without leaking data")], explanation: [b("Evalúa calidad antes del despliegue y monitoriza fallos después. Conserva entrada minimizada, versión, herramientas, latencia, coste y resultado cuando sea apropiado.", "Evaluate quality before deployment and monitor failures afterward. Retain minimized input, version, tools, latency, cost, and outcome where appropriate."), b("Los logs también son datos sensibles: aplica acceso, retención y redacción.", "Logs are sensitive data too: apply access control, retention, and redaction." )], practice: b("Crea diez evals y un esquema de traza para una función concreta.", "Create ten evals and a trace schema for one feature."), evidence: b("Resultados base, umbral y tres fallos explicados.", "Baseline results, threshold, and three explained failures."), sources: ["nist", "langgraph"], volatility: "volatile" }),
      lesson({ id: "seguridad-operacion", title: b("Seguridad y operación mínima", "Safety and minimum operations"), summary: b("Responsable, límites, copias y modo degradado.", "Owner, limits, backups, and degraded mode."), outcomes: [b("Preparar respuesta a fallos", "Prepare failure response"), b("Aplicar defensa por capas", "Apply defense in depth")], explanation: [b("Define quién responde, qué alertas importan, cómo se revocan credenciales, cómo se restaura una copia y cómo continúa el servicio sin IA.", "Define who responds, which alerts matter, how credentials are revoked, how a backup is restored, and how the service continues without AI."), b("Prueba inyección de prompts, datos maliciosos, abuso de herramientas y dependencia de proveedores.", "Test prompt injection, malicious data, tool abuse, and provider dependency." )], practice: b("Realiza un simulacro de caída y otro de entrada maliciosa.", "Run one outage drill and one malicious-input drill."), evidence: b("Runbook, tiempos, fallos observados y correcciones.", "Runbook, timings, observed failures, and fixes."), sources: ["owasp", "nist"], volatility: "reviewable" }),
      lesson({ id: "proyecto-final", title: b("Proyecto final: de problema a sistema fiable", "Capstone: from problem to reliable system"), summary: b("Integra utilidad, evidencia, seguridad y operación.", "Integrate usefulness, evidence, safety, and operations."), outcomes: [b("Entregar un sistema pequeño completo", "Deliver one small complete system"), b("Defender decisiones con pruebas", "Defend decisions with evidence")], explanation: [b("Elige un problema real y estrecho. Documenta usuario, datos, arquitectura mínima, riesgos, pruebas, coste, despliegue, mantenimiento y límites.", "Choose a real, narrow problem. Document user, data, minimum architecture, risks, tests, cost, deployment, maintenance, and limits."), b("El proyecto está terminado cuando otra persona puede ejecutarlo, comprobarlo y entender cuándo no debe usarlo.", "The project is complete when another person can run it, verify it, and understand when not to use it." )], practice: b("Construye, prueba y presenta el recorrido completo con datos ficticios o autorizados.", "Build, test, and present the full flow using fictional or authorized data."), evidence: b("Repositorio, demo, evals, threat model, runbook y retrospectiva.", "Repository, demo, evals, threat model, runbook, and retrospective."), sources: ["nist", "owasp", "eu"], volatility: "reviewable" }),
    ],
  },
];

export const localized = (value: Bilingual, locale: CourseLocale) => value[locale];
export const unifiedLessonCount = unifiedModules.reduce((total, module) => total + module.lessons.length, 0);

export const unifiedModuleProjects: Record<string, ModuleProject> = {
  fundamentos: {
    title: b("Mapa de una decisión asistida por IA", "Map an AI-assisted decision"),
    scenario: b("Una asociación quiere responder consultas frecuentes con IA, pero no sabe qué automatizar ni cómo comprobar las respuestas.", "A nonprofit wants to answer frequent questions with AI, but does not know what to automate or how to check answers."),
    deliverables: [b("Mapa de cinco tareas clasificadas por mecanismo.", "Map of five tasks classified by mechanism."), b("Protocolo de verificación para tres afirmaciones.", "Verification protocol for three claims."), b("Lista de acciones que la IA nunca realizará sola.", "List of actions the AI will never perform alone.")],
    checks: [b("Cada elección descarta una opción más simple con un motivo.", "Every choice rejects a simpler option with a reason."), b("Las fuentes permiten repetir la comprobación.", "Sources make the check reproducible."), b("Los límites describen comportamientos observables.", "Limits describe observable behavior.")],
  },
  trabajo: {
    title: b("Asistente de trabajo sin datos sensibles", "Work assistant without sensitive data"),
    scenario: b("Una persona administrativa quiere preparar borradores y resúmenes sin compartir nombres, contratos ni datos de clientes.", "An administrative worker wants to draft and summarize without sharing names, contracts, or customer data."),
    deliverables: [b("Plantilla con objetivo, contexto y aceptación.", "Template with goal, context, and acceptance."), b("Documento ficticio correctamente anonimizado.", "Properly anonymized fictional document."), b("Rutina humana antes de enviar o guardar.", "Human routine before sending or saving.")],
    checks: [b("El resultado puede revisarse con criterios visibles.", "The result can be reviewed with visible criteria."), b("No queda ningún identificador o secreto.", "No identifier or secret remains."), b("La decisión de enviar continúa siendo humana.", "The decision to send remains human.")],
  },
  "datos-rag": {
    title: b("Preguntas y respuestas sobre un manual", "Question answering over a handbook"),
    scenario: b("Un equipo necesita consultar un manual interno y saber exactamente de dónde procede cada respuesta.", "A team needs to query an internal handbook and know exactly where every answer comes from."),
    deliverables: [b("Corpus limpio con procedencia y fecha.", "Clean corpus with provenance and date."), b("Veinte preguntas, cuatro fuera de alcance.", "Twenty questions, four out of scope."), b("Informe separado de búsqueda, respuesta y citas.", "Separate retrieval, answer, and citation report.")],
    checks: [b("No se responde si falta el pasaje de apoyo.", "No answer is produced without a supporting passage."), b("Cada cita lleva al fragmento correcto.", "Every citation leads to the correct passage."), b("Los fallos están agrupados por causa.", "Failures are grouped by cause.")],
  },
  construir: {
    title: b("Web útil de principio a fin", "Useful website from start to finish"),
    scenario: b("Un profesional necesita explicar un servicio y recibir solicitudes sin exponer secretos ni publicar una interfaz rota.", "A professional needs to explain a service and receive requests without exposing secrets or shipping a broken interface."),
    deliverables: [b("Especificación y recorrido principal de una página.", "One-page specification and main journey."), b("Repositorio con diff y pruebas revisadas.", "Repository with reviewed diff and tests."), b("Preview, checklist móvil y rollback.", "Preview, mobile checklist, and rollback.")],
    checks: [b("Carga, vacío, error y éxito están diseñados.", "Loading, empty, error, and success are designed."), b("Teclado y móvil completan la tarea.", "Keyboard and mobile users complete the task."), b("No hay credenciales en cliente o repositorio.", "No credentials exist in client or repository.")],
  },
  local: {
    title: b("Informe de viabilidad para IA local", "Local AI feasibility report"),
    scenario: b("Una organización quiere saber si su equipo puede ejecutar un modelo local y qué tareas deben permanecer en una API.", "An organization wants to know whether its hardware can run a local model and which tasks should remain on an API."),
    deliverables: [b("Inventario de hardware y límites medidos.", "Hardware inventory and measured limits."), b("Comparación de dos modelos con la misma rúbrica.", "Two-model comparison with the same rubric."), b("Política local, API e híbrida por tarea.", "Local, API, and hybrid policy by task.")],
    checks: [b("Se registran versión, cuantización y memoria.", "Version, quantization, and memory are recorded."), b("La licencia se comprueba en la fuente original.", "The license is checked at the original source."), b("La decisión incluye mantenimiento y privacidad.", "The decision includes maintenance and privacy.")],
  },
  agentes: {
    title: b("Bandeja de entrada con aprobación", "Approval-based inbox workflow"),
    scenario: b("Una pyme quiere clasificar mensajes y preparar respuestas, pero ningún correo debe enviarse sin revisión.", "A small business wants to classify messages and draft replies, but no email may be sent without review."),
    deliverables: [b("Diagrama con estados, permisos y responsables.", "Diagram with states, permissions, and owners."), b("Contrato de herramientas de lectura y propuesta.", "Contract for read and proposal tools."), b("Prueba de reintento sin acciones duplicadas.", "Retry test without duplicated actions.")],
    checks: [b("Enviar es imposible antes de aprobar.", "Sending is impossible before approval."), b("Cada transición conserva una traza mínima.", "Every transition retains a minimum trace."), b("Existe un procedimiento manual alternativo.", "A manual fallback procedure exists.")],
  },
  produccion: {
    title: b("Defensa del proyecto final", "Capstone defense"),
    scenario: b("Debes demostrar que tu sistema resuelve un problema estrecho, falla de forma segura y puede mantenerlo otra persona.", "You must prove that your system solves a narrow problem, fails safely, and can be maintained by someone else."),
    deliverables: [b("Demo reproducible y repositorio documentado.", "Reproducible demo and documented repository."), b("Evals, modelo de amenazas, costes y límites.", "Evals, threat model, costs, and limits."), b("Runbook, restauración y retrospectiva.", "Runbook, restoration, and retrospective.")],
    checks: [b("Otra persona puede ejecutar y evaluar el sistema.", "Another person can run and evaluate the system."), b("Los casos peligrosos se bloquean o escalan.", "Dangerous cases are blocked or escalated."), b("La presentación incluye fallos reales.", "The presentation includes real failures.")],
  },
};
