import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Chapter, Objetivos, Idea, Cuidado, Comprueba, Guardar, ChapterNav } from "@/components/Book";

const titles: Record<string, string> = {
  "mapa-uso-responsable": "Mapa de usos responsables de IA en educación", "privacidad-menores": "Privacidad, menores y datos del centro", "objetivo-aprendizaje": "Define el objetivo antes de pedir materiales", "fuentes-y-sesgos": "Fuentes, sesgos y errores plausibles", "guias-ejercicios": "Genera una guía y ejercicios revisables", "niveles-diversidad": "Adapta una actividad a varios niveles", "accesibilidad": "Mejora accesibilidad sin inventar necesidades", "rubricas-auditables": "Construye rúbricas claras y auditables", "feedback-formativo": "Feedback formativo: orientar sin calificar a ciegas", "evaluacion-cerrada": "Diseña una evaluación que compruebe aprendizaje", "uso-indebido": "Uso indebido: prevención pedagógica, no vigilancia", "citas-y-verificacion": "Verifica respuestas y exige fuentes", "asistente-planificacion-local": "Crea un asistente local para planificar clases", "rag-temario-centro": "RAG sobre temarios y documentación propia", "piloto-con-equipo": "Ejecuta un piloto con revisión del equipo", "entrega-politica-aula": "Entrega una política de uso y evidencias",
};
const keys = Object.keys(titles);
const specifics: Record<string, { lead: string; action: string }> = {
  "mapa-uso-responsable": { lead: "No todo lo que la IA puede hacer debe delegarse en un aula.", action: "Clasifica diez tareas en asistida, revisada y no delegable; justifica cada decisión." },
  "privacidad-menores": { lead: "La protección de estudiantes empieza antes de copiar el primer nombre en un chat.", action: "Dibuja el flujo de datos y elimina nombres, identificadores y detalles innecesarios de un ejemplo." },
  "objetivo-aprendizaje": { lead: "Un buen prompt educativo comienza con lo que el alumno debe aprender.", action: "Escribe objetivo, evidencia y criterio de éxito antes de generar una actividad." },
  "fuentes-y-sesgos": { lead: "Una explicación fluida puede contener un error histórico, científico o cultural.", action: "Contrasta una respuesta con dos fuentes primarias y anota qué cambiarías." },
  "guias-ejercicios": { lead: "Genera un borrador que el docente pueda editar, no una ficha para imprimir sin mirar.", action: "Crea una guía con tres ejercicios, solución razonada y puntos de revisión." },
  "niveles-diversidad": { lead: "Adaptar no es bajar expectativas: es cambiar apoyos, lenguaje y andamiaje.", action: "Adapta una misma actividad a tres niveles y explica qué permanece constante." },
  "accesibilidad": { lead: "La IA puede proponer formatos accesibles, pero no diagnosticar ni etiquetar a una persona.", action: "Convierte una actividad a texto claro, lectura en voz alta y pasos visuales; revísala con el destinatario." },
  "rubricas-auditables": { lead: "Una rúbrica útil describe evidencias observables, no impresiones sobre el alumno.", action: "Crea cuatro criterios con tres niveles y un ejemplo de evidencia para cada uno." },
  "feedback-formativo": { lead: "El feedback debe abrir el siguiente intento, no sustituir la conversación docente.", action: "Genera comentarios que señalen logro, duda y siguiente paso sin poner una nota automática." },
  "evaluacion-cerrada": { lead: "La evaluación debe revelar aprendizaje propio, también cuando se usó IA para practicar.", action: "Diseña una parte abierta con IA y otra breve sin asistencia que compruebe comprensión." },
  "uso-indebido": { lead: "Perseguir textos no demuestra quién aprendió; diseñar mejores tareas sí mejora la evidencia.", action: "Reformula una tarea para exigir proceso, fuentes y defensa oral de decisiones." },
  "citas-y-verificacion": { lead: "Enseñar a verificar una respuesta es una competencia, no un trámite.", action: "Pide fuentes, comprueba dos afirmaciones y marca explícitamente una incertidumbre." },
  "asistente-planificacion-local": { lead: "Un asistente local puede ordenar una sesión sin conocer datos personales del alumnado.", action: "Crea un borrador con objetivo, tiempos, materiales y comprobación final usando datos ficticios." },
  "rag-temario-centro": { lead: "El asistente debe responder desde el temario autorizado y admitir cuando no lo encuentra.", action: "Indexa dos documentos propios con permisos y exige una cita de página en cada respuesta." },
  "piloto-con-equipo": { lead: "Un piloto educativo necesita varias miradas, límites y una fecha de revisión.", action: "Prueba la actividad con dos docentes, registra fallos y decide si continúa, cambia o se detiene." },
  "entrega-politica-aula": { lead: "La política debe explicar usos permitidos, revisión, privacidad y qué hacer cuando la IA falla.", action: "Entrega una política de una página, una rúbrica y tres evidencias del piloto." },
};

export function generateStaticParams() { return keys.map((lesson) => ({ lesson })); }
export async function generateMetadata({ params }: { params: Promise<{ lesson: string }> }): Promise<Metadata> { const { lesson } = await params; const title = titles[lesson]; return title ? { title: `${title} | Aulafy`, description: specifics[lesson].lead, alternates: { canonical: `/cursos/ia-docentes-educacion/${lesson}` } } : {}; }
export default async function Page({ params }: { params: Promise<{ lesson: string }> }) { const { lesson } = await params; const title = titles[lesson]; if (!title) notFound(); const item = specifics[lesson]; const index = keys.indexOf(lesson); const next = keys[index + 1]; return <Chapter crumb="IA para docentes y educación" title={title} icon="book" lead={item.lead} courseHref="/cursos/ia-docentes-educacion" courseLabel="IA para docentes y educación"><Objetivos><ul><li>Convertir una decisión educativa en una acción concreta.</li><li>Revisar el resultado con criterio docente.</li><li>Guardar una evidencia reutilizable y proteger los datos.</li></ul></Objetivos><div className="prose"><p>La IA es una herramienta de apoyo: no sustituye la relación educativa, el juicio profesional ni la responsabilidad del centro. Trabaja con ejemplos ficticios, separa borrador de decisión y documenta qué revisaste.</p></div><Idea><strong>Acción de la misión:</strong> {item.action}</Idea><Cuidado>No introduzcas datos identificables de menores ni uses una salida automática como calificación final. Consulta la política del centro y la normativa aplicable.</Cuidado><Comprueba>Guarda el prompt, el borrador, la revisión humana y una versión final que otra persona pueda inspeccionar.</Comprueba><Guardar>Registra fecha, herramienta/modelo, fuentes, datos usados y qué parte sigue siendo responsabilidad docente.</Guardar><ChapterNav next={next ? { href: `/cursos/ia-docentes-educacion/${next}`, label: titles[next] } : undefined} /></Chapter>; }
