-- Aulafy Brain M0.1. Canonical content remains in Git; these tables are its
-- relational index plus learning, evidence and future-operation records.
begin;

create table if not exists public.aulafy_courses (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, description text, status text not null default 'published', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_courses_status check (status in ('draft','published','archived')));
create table if not exists public.aulafy_modules (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.aulafy_courses(id) on delete restrict, slug text not null, title text not null, position integer not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(course_id, slug), unique(course_id, position));
create table if not exists public.aulafy_lessons (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.aulafy_modules(id) on delete restrict, content_id text not null unique, slug text not null, title text not null, description text, level text, estimated_minutes integer, content_hash text, content_version integer not null default 1, status text not null default 'published', published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(module_id, slug), constraint aulafy_lessons_minutes check (estimated_minutes is null or estimated_minutes > 0), constraint aulafy_lessons_version check (content_version > 0), constraint aulafy_lessons_status check (status in ('draft','published','archived')));

create table if not exists public.aulafy_concepts (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, description text, status text not null default 'published', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_concepts_status check (status in ('draft','published','archived')));
create table if not exists public.aulafy_concept_relations (id uuid primary key default gen_random_uuid(), source_concept_id uuid not null references public.aulafy_concepts(id) on delete restrict, target_concept_id uuid not null references public.aulafy_concepts(id) on delete restrict, relation_type text not null, created_at timestamptz not null default now(), unique(source_concept_id,target_concept_id,relation_type), constraint aulafy_relations_self check (source_concept_id <> target_concept_id), constraint aulafy_relations_type check (relation_type in ('REQUIRES','PART_OF','RELATED_TO','BUILDS_ON','ALTERNATIVE_TO')));
create table if not exists public.aulafy_lesson_concepts (lesson_id uuid not null references public.aulafy_lessons(id) on delete restrict, concept_id uuid not null references public.aulafy_concepts(id) on delete restrict, role text not null default 'primary', primary key(lesson_id,concept_id), constraint aulafy_lesson_concepts_role check (role in ('primary','secondary','prerequisite')));
create table if not exists public.aulafy_skills (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, description text, status text not null default 'published', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_skills_status check (status in ('draft','published','archived')));
create table if not exists public.aulafy_lesson_skills (lesson_id uuid not null references public.aulafy_lessons(id) on delete restrict, skill_id uuid not null references public.aulafy_skills(id) on delete restrict, primary key(lesson_id,skill_id));

create table if not exists public.aulafy_projects (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, description text, difficulty text, status text not null default 'published', estimated_minutes integer, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_projects_difficulty check (difficulty is null or difficulty in ('beginner','intermediate','advanced')), constraint aulafy_projects_status check (status in ('draft','published','archived')));
create table if not exists public.aulafy_project_concepts (project_id uuid not null references public.aulafy_projects(id) on delete restrict, concept_id uuid not null references public.aulafy_concepts(id) on delete restrict, primary key(project_id,concept_id));
create table if not exists public.aulafy_project_skills (project_id uuid not null references public.aulafy_projects(id) on delete restrict, skill_id uuid not null references public.aulafy_skills(id) on delete restrict, primary key(project_id,skill_id));
create table if not exists public.aulafy_exercises (id uuid primary key default gen_random_uuid(), lesson_id uuid references public.aulafy_lessons(id) on delete restrict, concept_id uuid references public.aulafy_concepts(id) on delete restrict, skill_id uuid references public.aulafy_skills(id) on delete restrict, slug text not null unique, title text not null, exercise_type text not null, status text not null default 'published', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_exercises_type check (exercise_type in ('multiple_choice','short_answer','code','task')), constraint aulafy_exercises_status check (status in ('draft','published','archived')), constraint aulafy_exercises_target check (lesson_id is not null or concept_id is not null or skill_id is not null));
create table if not exists public.aulafy_evaluations (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, evaluation_type text not null, concept_id uuid references public.aulafy_concepts(id) on delete restrict, skill_id uuid references public.aulafy_skills(id) on delete restrict, project_id uuid references public.aulafy_projects(id) on delete restrict, status text not null default 'published', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_evaluations_type check (evaluation_type in ('concept','skill','project','content','retrieval','tutor','dataset','model')), constraint aulafy_evaluations_status check (status in ('draft','published','archived')), constraint aulafy_evaluations_target check (concept_id is not null or skill_id is not null or project_id is not null));

create table if not exists public.aulafy_profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.aulafy_user_lesson_progress (user_id uuid not null references auth.users(id) on delete cascade, lesson_id uuid not null references public.aulafy_lessons(id) on delete restrict, status text not null default 'not_started', started_at timestamptz, completed_at timestamptz, last_activity_at timestamptz not null default now(), primary key(user_id,lesson_id), constraint aulafy_progress_status check (status in ('not_started','in_progress','completed')));
create table if not exists public.aulafy_user_concept_mastery (user_id uuid not null references auth.users(id) on delete cascade, concept_id uuid not null references public.aulafy_concepts(id) on delete restrict, mastery_score numeric(5,4) not null default 0, confidence_score numeric(5,4) not null default 0, evidence_count integer not null default 0, last_evaluated_at timestamptz, updated_at timestamptz not null default now(), primary key(user_id,concept_id), constraint aulafy_concept_mastery_range check (mastery_score between 0 and 1 and confidence_score between 0 and 1), constraint aulafy_concept_mastery_count check (evidence_count >= 0));
create table if not exists public.aulafy_user_skill_mastery (user_id uuid not null references auth.users(id) on delete cascade, skill_id uuid not null references public.aulafy_skills(id) on delete restrict, mastery_score numeric(5,4) not null default 0, confidence_score numeric(5,4) not null default 0, evidence_count integer not null default 0, last_evaluated_at timestamptz, updated_at timestamptz not null default now(), primary key(user_id,skill_id), constraint aulafy_skill_mastery_range check (mastery_score between 0 and 1 and confidence_score between 0 and 1), constraint aulafy_skill_mastery_count check (evidence_count >= 0));
create table if not exists public.aulafy_evidence (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, evidence_type text not null, status text not null default 'submitted', payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), verified_at timestamptz, constraint aulafy_evidence_type check (evidence_type in ('lesson_completion','exercise_result','evaluation_result','project_submission','code','repository','file','screenshot','cli_output','manual_review')), constraint aulafy_evidence_status check (status in ('submitted','verified','rejected','superseded')));
create table if not exists public.aulafy_evidence_targets (evidence_id uuid not null references public.aulafy_evidence(id) on delete restrict, lesson_id uuid references public.aulafy_lessons(id) on delete restrict, exercise_id uuid references public.aulafy_exercises(id) on delete restrict, project_id uuid references public.aulafy_projects(id) on delete restrict, evaluation_id uuid references public.aulafy_evaluations(id) on delete restrict, constraint aulafy_evidence_one_target check (num_nonnulls(lesson_id,exercise_id,project_id,evaluation_id) = 1));

create table if not exists public.aulafy_knowledge_sources (id uuid primary key default gen_random_uuid(), source_type text not null, name text not null, url text, canonical boolean not null default false, verified boolean not null default false, license text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_sources_type check (source_type in ('aulafy_canonical','official_documentation','research_paper','external_source','ai_generated','user_generated')));
create table if not exists public.aulafy_knowledge_documents (id uuid primary key default gen_random_uuid(), source_id uuid not null references public.aulafy_knowledge_sources(id) on delete restrict, external_id text, title text not null, uri text, content_hash text not null, content_version integer not null default 1, status text not null default 'active', published_at timestamptz, retrieved_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(source_id,external_id), constraint aulafy_documents_status check (status in ('draft','active','archived')));
create table if not exists public.aulafy_knowledge_chunks (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.aulafy_knowledge_documents(id) on delete restrict, chunk_index integer not null, content text not null, content_hash text not null, token_count integer, embedding_model text, embedding_version text, created_at timestamptz not null default now(), unique(document_id,chunk_index), constraint aulafy_chunks_index check (chunk_index >= 0));
create table if not exists public.aulafy_knowledge_chunk_concepts (chunk_id uuid not null references public.aulafy_knowledge_chunks(id) on delete restrict, concept_id uuid not null references public.aulafy_concepts(id) on delete restrict, primary key(chunk_id,concept_id));

create table if not exists public.aulafy_ingestion_runs (id uuid primary key default gen_random_uuid(), source_type text not null, status text not null default 'pending', started_at timestamptz, completed_at timestamptz, documents_seen integer not null default 0, documents_created integer not null default 0, documents_updated integer not null default 0, chunks_created integer not null default 0, error_count integer not null default 0, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), constraint aulafy_ingestion_status check (status in ('pending','running','success','partial','failed')));
create table if not exists public.aulafy_evaluation_runs (id uuid primary key default gen_random_uuid(), evaluation_id uuid references public.aulafy_evaluations(id) on delete restrict, run_type text not null, status text not null default 'pending', started_at timestamptz, completed_at timestamptz, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), constraint aulafy_eval_runs_type check (run_type in ('content','retrieval','tutor','dataset','model')), constraint aulafy_eval_runs_status check (status in ('pending','running','success','partial','failed')));
create table if not exists public.aulafy_dataset_candidates (id uuid primary key default gen_random_uuid(), candidate_type text not null, instruction text not null, input text, output text not null, quality_score numeric(5,4), review_status text not null default 'candidate', source_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), reviewed_at timestamptz, constraint aulafy_dataset_status check (review_status in ('candidate','approved','rejected','superseded')), constraint aulafy_dataset_quality check (quality_score is null or quality_score between 0 and 1));
create table if not exists public.aulafy_dataset_candidate_sources (candidate_id uuid not null references public.aulafy_dataset_candidates(id) on delete restrict, lesson_id uuid references public.aulafy_lessons(id) on delete restrict, chunk_id uuid references public.aulafy_knowledge_chunks(id) on delete restrict, exercise_id uuid references public.aulafy_exercises(id) on delete restrict, project_id uuid references public.aulafy_projects(id) on delete restrict, evaluation_id uuid references public.aulafy_evaluations(id) on delete restrict, constraint aulafy_dataset_one_source check (num_nonnulls(lesson_id,chunk_id,exercise_id,project_id,evaluation_id) = 1));
create table if not exists public.aulafy_learning_paths (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, description text, status text not null default 'published', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint aulafy_paths_status check (status in ('draft','published','archived')));
create table if not exists public.aulafy_learning_path_items (id uuid primary key default gen_random_uuid(), path_id uuid not null references public.aulafy_learning_paths(id) on delete restrict, position integer not null, lesson_id uuid references public.aulafy_lessons(id) on delete restrict, exercise_id uuid references public.aulafy_exercises(id) on delete restrict, project_id uuid references public.aulafy_projects(id) on delete restrict, evaluation_id uuid references public.aulafy_evaluations(id) on delete restrict, unique(path_id,position), constraint aulafy_path_one_target check (num_nonnulls(lesson_id,exercise_id,project_id,evaluation_id) = 1));

create index if not exists aulafy_modules_course_idx on public.aulafy_modules(course_id);
create index if not exists aulafy_lessons_module_idx on public.aulafy_lessons(module_id);
create index if not exists aulafy_progress_user_idx on public.aulafy_user_lesson_progress(user_id);
create index if not exists aulafy_evidence_user_idx on public.aulafy_evidence(user_id,created_at desc);
create index if not exists aulafy_documents_hash_idx on public.aulafy_knowledge_documents(content_hash);
create index if not exists aulafy_chunks_document_idx on public.aulafy_knowledge_chunks(document_id);
create index if not exists aulafy_dataset_review_idx on public.aulafy_dataset_candidates(review_status);

alter table public.aulafy_courses enable row level security; alter table public.aulafy_modules enable row level security; alter table public.aulafy_lessons enable row level security; alter table public.aulafy_concepts enable row level security; alter table public.aulafy_skills enable row level security; alter table public.aulafy_projects enable row level security; alter table public.aulafy_knowledge_sources enable row level security; alter table public.aulafy_knowledge_documents enable row level security; alter table public.aulafy_knowledge_chunks enable row level security; alter table public.aulafy_learning_paths enable row level security; alter table public.aulafy_learning_path_items enable row level security; alter table public.aulafy_user_lesson_progress enable row level security; alter table public.aulafy_user_concept_mastery enable row level security; alter table public.aulafy_user_skill_mastery enable row level security; alter table public.aulafy_evidence enable row level security;

create policy aulafy_courses_read on public.aulafy_courses for select using (status = 'published');
create policy aulafy_modules_read on public.aulafy_modules for select using (true);
create policy aulafy_lessons_read on public.aulafy_lessons for select using (status = 'published');
create policy aulafy_concepts_read on public.aulafy_concepts for select using (status = 'published');
create policy aulafy_skills_read on public.aulafy_skills for select using (status = 'published');
create policy aulafy_projects_read on public.aulafy_projects for select using (status = 'published');
create policy aulafy_sources_read on public.aulafy_knowledge_sources for select using (verified = true);
create policy aulafy_documents_read on public.aulafy_knowledge_documents for select using (status = 'active');
create policy aulafy_chunks_read on public.aulafy_knowledge_chunks for select using (true);
create policy aulafy_paths_read on public.aulafy_learning_paths for select using (status = 'published');
create policy aulafy_path_items_read on public.aulafy_learning_path_items for select using (true);
create policy aulafy_progress_own on public.aulafy_user_lesson_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy aulafy_concept_mastery_own on public.aulafy_user_concept_mastery for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy aulafy_skill_mastery_own on public.aulafy_user_skill_mastery for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy aulafy_evidence_own on public.aulafy_evidence for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

commit;
